### PR TITLE
[WIP] Add support for using Annoy as an external similarity index

### PR DESCRIPTION
**Pull request by karlhigley**
(Related to #617, #527, and #51.)

This is a partial implementation of an external similarity index based on Annoy for approximate nearest neighbor search. It's based on #617 and the related comments, using a test-first approach. I'm running out of time to pursue it during the PyCon sprints, but wanted to share the pieces that may be useful for pushing #617 forward (e.g. class method index construction, conditional Annoy dependency in the tests).

### CODE REVIEW

**Comment by karlhigley** [comment]
@tmylk: I had a bit of trouble with Doc2Vec during the sprints, but I think I figured out a way to do it.

**Comment by karlhigley** [comment]
It looks like the tests don't run on Travis, since Annoy is not installed there. Not sure how to fix the test failure in Python 2.6 either.

**Comment by karlhigley** [comment]
(Nevermind, #758 added annoy.)

**Comment by tmylk** [comment]
Implemented in #784 and others

**Pull request closed without merging**
