### PR TITLE
Fix pure python implementation of doc2vec (w/online-learning). Partial fix #1019

### LINKED ISSUE #1019: Segmentation fault when performing online learning for Doc2Vec
Hello!

I'm performing online learning for `Doc2Vec`, that is, I learn an initial model on a set of tagged documents and try to update the model on a new set of tagged documents. If the second set contains new tags (tags that were not present in the initial set of documents), then I usually get segmentation fault (this behavior is not deterministic, but it happens most of time).

Below you can find a toy example that reproduces the issue; and [here](http://pastebin.com/dNUyAnAD) is the output of that code. I'm using Python 3.4.3 and Gensim 0.13.3.

I've debugged with gdb and I've got the following output:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff9a4f8700 (LWP 29422)]
__pyx_f_6gensim_6models_13doc2vec_inner_fast_document_dm_hs (__pyx_v_learn_hidden=1, __pyx_v_size=300, __pyx_v_work=0x7fff80001480, __pyx_v_alpha=0.0250000004, __pyx_v_syn1=0x1693ce0, __pyx_v_neu1=0x7fff80001a00, __pyx_v_word_code_len=6,
    __pyx_v_word_code=<optimized out>, __pyx_v_word_point=0x13fe410) at ./gensim/models/doc2vec_inner.c:2078
```

I'm willing to help fixing this issue if someone can provide me some guidance. Thanks!

Sample code that reproduces the issue:

```python
import logging

from gensim.models.doc2vec import (
    Doc2Vec,
    TaggedDocument,
)

logging.basicConfig(
    format='%(asctime)s : %(threadName)s : %(levelname)s : %(message)s',
    level=logging.DEBUG,
)


def to_str(d):
    return ", ".join(d.keys())


SENTS = [
    "anecdotal using a personal experience or an isolated example instead of a sound argument or compelling evidence",
    "plausible thinking that just because something is plausible means that it is true",
    "occam razor is used as a heuristic technique discovery tool to guide scientists in the development of theoretical models rather than as an arbiter between published models",
    "karl popper argues that a preference for simple theories need not appeal to practical or aesthetic considerations",
    "the successful prediction of a stock future price could yield significant profit",
]

SENTS = [s.split() for s in SENTS]


def main():
    sentences_1 = [
        TaggedDocument(SENTS[0], tags=['SENT_0']),
        TaggedDocument(SENTS[1], tags=['SENT_0']),
        TaggedDocument(SENTS[2], tags=['SENT_1']),
    ]

    sentences_2 = [
        TaggedDocument(SENTS[3], tags=['SENT_1']),
        TaggedDocument(SENTS[4], tags=['SENT_2']),
    ]

    model = Doc2Vec(min_count=1, workers=1)

    model.build_vocab(sentences_1)
    model.train(sentences_1)

    print("-- Base model")
    print("Vocabulary:", to_str(model.vocab))
    print("Tags:", to_str(model.docvecs.doctags))

    model.build_vocab(sentences_2, update=True)
    model.train(sentences_2)

    print("-- Updated model")
    print("Vocabulary:", to_str(model.vocab))
    print("Tags:", to_str(model.docvecs.doctags))


if __name__ == '__main__':
    main()
```

### PR DESCRIPTION
**Pull request by mino98**
As of #1019, this fixes the slow implementation of Doc2Vec and enables online-learning on new documents.

Tested on [this](https://gist.github.com/mino98/f876cff1f747cdd0b858b7a7d995e2f9). Please make sure that you are using the "slow version" before testing (to do so, I delete `gensim/models/doc2vec_inner.c` before building/installing. Maybe there's a simpler method 😄 ).

### CODE REVIEW

**Comment by menshikh-iv** [comment]
#1777 should be merged first, @mino98 sorry for waiting.

**Comment by mino98** [comment]
Of course, no problem @menshikh-iv, but [here](https://github.com/manneshiva/gensim/wiki/Any2Vec-Refactoring-Summary) I read:
> Drops pure Python implementations and FastText wrapper.

which will make this PR useless in the first place. By the way, are "online learning" and vocabulary expansions taken into consideration in the new *2vec architecture?

**Comment by menshikh-iv** [comment]
@mino98 About dropping python support - yes, we'll do this, but slightly later (after #1777). Anyway, your code will exist very little time, sorry.

About architecture: online-learning - yes, vocab expansion - possible.

**Comment by mino98** [comment]
> About architecture: online-learning - yes, vocab expansion - possible.

Great, but I'd like to stress that online-learning without vocab expansion is useless for many (all?) practical purposes.

I don't particularly care for my code, as long as post-#1777 we implement these two features.

**Comment by menshikh-iv** [comment]
> Great, but I'd like to stress that online-learning without vocab expansion is useless for many (all?) practical purposes.

So, I don't agree with you. This needed for training on really large corpuses (when training process needs several days/weeks). 

Vocab expansion is really hard to implement well IMO.

**Comment by mino98** [comment]
I think we mean different things by _online learning_: for me it means "being able of updating the model on a completely new corpus, to improve/finetune it", for you it is "checkpoint/snapshot the model during long training so that you can save/restart it".

Thanks.

**Comment by menshikh-iv** [comment]
@mino98 not quiet, "online" for me means that I no need full train data at one moment (I can pass it sentence by sentence). Also, I can save model, load and continue training with any data.

You talking about changing dictionary in training time, am I right (i.e. you pass fresh data and add words that you never see in the model during training process)?

**Comment by mino98** [comment]
> You talking about changing dictionary in training time, am I right (i.e. you pass fresh data and add words that you never see in the model during training process)?

Correct: I'm referring to training with documents that include words not present in the set of previously seen documents.

In real world experiments, this happens all the time. Imagine for example:
1. start with a new model (i.e., all initial weights are random)
2. `build_vocab()` + `train()` on a corpus of 100 books. Once completed, `save()` the model to storage.
3. some time later, you get 20 new books that you want to include in the model. So, I `load()` the model from disk, do `build_vocab(update=True)` on the new corpus, then `train()` on it and `save()` it back to disk.

Once in a while you need to repeat step 3. Say, for example, every week. Or every 12 hours. Or every time you get a decent amount of fresh user content... You clearly don't want (or cannot) to re-train on the whole corpus (i.e., 100+20+... books) from zero every time.

Those "20 new books" will for sure contain new words not present in the initial 100 books, which will force you to extend the vocabulary, right?

(ps: thanks for this discussion. Maybe I'm misunderstanding how you do online learning in gensim?)

**Comment by menshikh-iv** [comment]
@mino98 #1777 merged successfully, please resolve merge-conflict

**Comment by menshikh-iv** [comment]
ping @mino98, are you planning to finish PR?

**Comment by mino98** [comment]
Sorry for the delay @menshikh-iv, realistically I won't have time for this for some time. 

By the way, I assumed that #1777 was going to drop completely the pure-python implementations, so this PR would become useless in the first place?

**Comment by menshikh-iv** [comment]
@mino98 no, we still support pure-python (until the major release), but it's completely up to you. If you can't finish this - please close PR.

**Comment by menshikh-iv** [comment]
Anyway, thanks for your good work @mino98  :+1:, sorry for this situation.

**Comment by mino98** [comment]
Don't worry @menshikh-iv and thanks, Gensim is a great project.

However, it's not worth investing more effort to untangle this PR: the Python-only implementation is too slow for some practical purposes and going to be dropped at the next major release anyway, so...

**Comment by menshikh-iv** [comment]
@mino98 this PR can be used as the base for Cython version :+1:

**Pull request closed without merging**
