### PR TITLE
Initialize self.cfs in Dictionary.compatify method

### LINKED ISSUE #2574: Dictionary gensim.corpora should update the collection frequencies cfs after filtering with filter_extremes
#### Problem description

I am using the Dictionary class gensim.corpora.dictionary.Dictionary , in particular the filter_extremes method and the cfs property (returning a collection frequencies dictionary mapping token_id to tokenfrequency). 
It appears that after using  filter_extremes, the cfs still shows unfiltered token_id's can be absent from the filtered Dictionary instance. This can lead to KeyErrors. 

#### Steps to reproduce

```python
from gensim.corpora import Dictionary
corpus = [['common','single'],['common']]
dct = Dictionary(corpus)
len(dct)  #2
dct.cfs   #{0: 2, 1: 1}
dct.filter_extremes(no_below=1, no_above=0.5, keep_n=1)
len(dct)  #1
dct.cfs   #{1: 1}
dct[1]
```

The last line fails with 'KeyError: 1', as the filtered Dictionary has only one element. I suspect the cfs dictionary should be updated once the Dictionary instance dct gets filtered by filter_extremes. The documentation has this warning for the filter_extremes method, but I do not think it is relevant for this case: "After the pruning, resulting gaps in word ids are shrunk. Due to this gap shrinking, the same word may have a different word id before and after the call to this function!"

#### Versions

Please provide the output of:

```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)

Linux-4.15.0-50-generic-x86_64-with-LinuxMint-19-tara
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
NumPy 1.16.3
SciPy 0.19.1
gensim 3.8.0
FAST_VERSION 1
```

### PR DESCRIPTION
**Pull request by SanthoshBala18**
Fix #2574

### CODE REVIEW

**Comment by galtay** [comment]
was going to file an issue, but then found this one https://github.com/RaRe-Technologies/gensim/issues/2574 and this PR.  does triage mean it just needs approval to be merged?

**Comment by piskvorky** [comment]
Yeah, but @mpenkov is busy these days, so it may take a little while. New release may have to wait for after Christmas, sorry.

**Comment by galtay** [comment]
no need to apologize, thank you both for the great open source tools!

**Comment by mpenkov** [comment]
Merged. Thank you for your contribution!

**Pull request merged**
