### PR TITLE
[WIP] Adding docker containers in Gensim. Fix #497

### LINKED ISSUE #497: Pre-installed container image with gensim
Use Docker (or similar) technology to distribute a turn-key environment for trying out gensim.

Discussed on the [mailing list](https://groups.google.com/forum/#!searchin/gensim/docker/gensim/DYad1y74ZQA/gCXZZwKWDAoJ) but never realized. CC @svanschalkwyk.

The goals are:
- no extra installations (all dependencies already there)
- includes a data set for trying things out, along with instructions / tutorial scripts
- other?

### PR DESCRIPTION
**Pull request by danielbdias**
I am adding a docker image to run gensim tutorials.

In this PR I created a Dockerfile with Ubuntu 16.04, Python 3 and gensim dependencies and a docker-compose.yml to run the jupyter notebooks.

### CODE REVIEW

**Comment by tmylk** [comment]
Thanks for the contribution.
Remaining steps:

- [ ] docker hub upload
- [ ] transfer credentials for docker hub container

**Comment by danielbdias** [comment]
Hi guys ! 

I updated the PR with the check in the FAST_VERSION and a README.md to pull this image in docker hub.

Now I need to fix some problems when we are pushing this image directly from docker hub. (Running the image gives a `container_linux.go:247: starting container process caused "exec: \"-p\": executable file not found in $PATH"` error)

After that, we need to create an official image we will need to create a PR to https://github.com/docker-library/official-images and https://github.com/docker-library/docs

**Comment by danielbdias** [comment]
Another update: I fixed the problem with docker hub, but now we need to refer to a fixed version of gensim.

For now I created an image called danielbdias/gensim in docker hub to test the environment.

Can you check if all the setup in the Dockerfile is ok? With docker file ok, I will start to apply the [missing guidelines](https://github.com/docker-library/official-images/blob/master/README.md#review-guidelines) to start the PR in docker-library/official-images and build the official container.

**Comment by candidk** [comment]
consider including binaries for wordrank and fasttext

**Comment by tmylk** [comment]
And varembed, mallet, dtm

**Comment by danielbdias** [comment]
Hi guys,

I've found the installation commands for mallet and fasttext (through pip). How can I install the other packages (wordrank, varembed and dtm)?

**Comment by tmylk** [comment]
https://bitbucket.org/shihaoji/wordrank

https://github.com/rguthrie3/MorphologicalPriorsForWordEmbeddings

https://github.com/fedorn/dtm

**Comment by tmylk** [comment]
Mallet is actually a java package so it can't be installed through pip 
http://mallet.cs.umass.edu/

**Comment by danielbdias** [comment]
Hi guys ! 

Giving some updates on this issue after a while: I've updated the dockerfile to support WordRank, MorphologicalPriorsForWordEmbeddings, DTM and Mallet.

Is there a issue yet with the FAST_VERSION... some dependency broke the version.

Fixing this problem, I'll be able to upload a version to docker hub and create a gensim user there.

Thanks !

**Comment by tmylk** [comment]
Thanks @danielbdias What is the exact error with FAST_VERSION? Does the new version of the C compiler not work?

**Comment by tmylk** [comment]
This docker will be really useful for testing the wrappers during releases.

**Comment by danielbdias** [comment]
Hi @tmylk ! I'm receiving FAST_VERSION = -5 when I'm building the docker. I think that the reason is the dependencies that I installed for WordRank, MorphologicalPriorsForWordEmbeddings.

I will check this weekend on a way to solve this.

**Comment by menshikh-iv** [comment]
It's a nice PR, I would like use this for full test run (with all wrappers)

**Comment by tmylk** [comment]
This container will be part of our release infrastructure as we need to run all the wrapper tests every release and they are not part of the usual Github commit CI run.

**Comment by menshikh-iv** [comment]
Continues in [#1368](https://github.com/RaRe-Technologies/gensim/pull/1368)

**Pull request closed without merging**
