### PR TITLE
remove gensim.summarization subpackage, docs and test data

### LINKED ISSUE #2592: Discussion: discard "gensim.summarization"?
In the course of considering the list question at <https://groups.google.com/d/msg/gensim/v24RI3-oUq0/NYlPpif1AQAJ>, I took a slightly-deeper look at `gensim.summarization` than before. 

From that look, my opinion is that its presence is more likely to waste peoples' time than help them. It's fairly rudimentary functionality, but spread across many files, with its own non-configurable regex-based word- and sentence- tokenization, with a lot of hard-to-follow steps. None of the doc/tutorial examples show impressive results.  

I even find it hard to imagine anyone getting satisfactory results from this approach, so I expect most peoples' interaction with this code is: (1) "I need summarization – and cool, gensim has a summarization feature!" (2) View its docs/tutorial and try on some real data. (3) "This is nowhere near what I need nor is it customizable/fixable enough to be tweaked into service." (4) They look for something else entirely.

I'd suggest marking the whole module 'deprecated' with an eye towards eventual removal. And, if summarization is an important thing to truly support, soliciting someone to work-up a better algorithm or implementation, one that can actually demo some useful results in a tutorial/demo, and that also mixes well with other corpus-format/tokenization practices in gensim. (It might even be TextRank-based – but with configurable tokenization & sentence-similarity/graph-building steps.)

### PR DESCRIPTION
**Pull request by mpenkov**
fix #2592

### CODE REVIEW

**Comment by piskvorky** [comment]
Can you update https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4 with the motivation please?

That doc will be my starting point for further write-ups, clean ups, guides etc. Thanks!

Also, what about other modules? We talked about axing a bunch: HDP, wrappers etc.

**Comment by piskvorky** [comment]
@mpenkov ping. I'm migrating all the tutorials and how-tos for 4.0 now, and would really prefer to avoid working on stuff that will be immediately removed.

If this can be merged please merge + update the wiki + any other modules to remove? Thanks.

**Comment by piskvorky** [comment]
@mpenkov update: I went through all tutorials & how-tos in #2968; `run_distance_metrics.py` and `run_pivoted_normalization.py` can be axed too. Poor inarticulate code accompanied by poor inarticulate text (and that's after we'd already gone through it and fixed stuff!)

Can you please get rid of them? Along with any code / modules that accompany them, and any other docs that point to them. We don't want contributions of such "quality" in Gensim. Thanks!

**Comment by mpenkov** [comment]
> Also, what about other modules? We talked about axing a bunch: HDP, wrappers etc.

Can we do this in a separate PR (or PRs)? I'm doing this work in short bursts due to lack of time, and if we keep everything in one PR, it'll stretch out over time and add a lot of overhead.

**Comment by piskvorky** [comment]
Of course!

**Comment by piskvorky** [comment]
@mpenkov was this done? I cannot find any info in the CHANGELOG nor the Migration notes. And I don't see any link here either.

Can you document what was actually removed & where? What about wrappers like `mallet`, `vw`, `dt`, `ldaseq`?

**Pull request merged**
