### PR TITLE
Fixed Typo and increased performance in analyze_sentence

### PR DESCRIPTION
**Pull request by JonathanHourany**
Type on  line 147. Sentence is "...happy ending has it won't..." where "has" should be "as"

### CODE REVIEW

**Comment by JonathanHourany** [comment]
Fixing a minor typo

**Comment by piskvorky** [comment]
Thanks @JonathanHourany . Looking at the code, that whole "trick" is questionable though -- adding two lists together will create a new list, which is a very costly operation in such a tight spot.

So I don't think that's a good idea in the first place, but we wanted to replace that code by an optimized Cython loop anyway…

**Comment by JonathanHourany** [comment]
I agree, seems it'd be better to append `None` instead. If a Cython implementation is far off I could make the change in a new commit if you feel it's worth it.

**Comment by piskvorky** [comment]
Yes please!

**Comment by piskvorky** [comment]
Thanks @JonathanHourany !

**Comment by JonathanHourany** [comment]
Thank you!

**Pull request merged**
