### PR TITLE
refactor syn0 initialization

### PR DESCRIPTION
**Pull request by stegben**
I slightly refactor the initialization of `syn0` of `KeyedVectors` in order to support memmap in the future (if possible).

### CODE REVIEW

**Comment by stegben** [comment]
Any suggestion or roadmap for supporting memmap?

**Comment by menshikh-iv** [comment]
@stegben can you add more motivation, why this needed / useful?

**Comment by gojomo** [comment]
Note that there's some bigger refactoring on the way via #1777, which may change the name of `syn0` (a holdover from the class's origin inside W2V NN models).

**Comment by menshikh-iv** [comment]
Thanks for reminder @gojomo, so, I think we should merge #1777 first (in any case).

About this PR - I'm waiting additional comments from @stegben

**Comment by menshikh-iv** [comment]
ping @stegben

**Comment by menshikh-iv** [comment]
I close this PR because it looks abadoned.

**Pull request closed without merging**
