### PR TITLE
Update the licence link to  LGPLv2.1

### PR DESCRIPTION
**Pull request by ERijck**

### CODE REVIEW

**Comment by piskvorky** [comment]
@pabs3 CC – please review.

**Comment by piskvorky** [comment]
Whoa, what's going on. Why is the PR so large?

**Comment by pabs3** [comment]
Looks like @ERijck merged `main` back into the `my_flsa_fixes` branch they used to submit this PR, making it huge. I suggest closing this PR, rebasing instead of merging and then resubmitting the PR.

https://github.com/RaRe-Technologies/gensim/compare/develop...ERijck:gensim:my_flsa_fixes

**Comment by PabloMosUU** [comment]
I am a collaborator of @ERijck . We have undone the merge that had caused the big pull request. The change is now only the license change, as you can see. Is this sufficient to merge the pull request?

**Comment by mpenkov** [comment]
@piskvorky Should be good to merge now, right?

**Pull request merged**
