### PR TITLE
Corpus streaming tutorial changes

### PR DESCRIPTION
**Pull request by charliejharrison**
Made some minor changes to the text of the tutorial.  I'd also suggest changing the name of the notebook from "Corpora_and_Vector_Spaces.ipynb" to "Corpus_Streaming.ipynb" to reflect the main content.

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Thank you for your PR, I think all ok, @tmylk can you merge this PR?

**Comment by tmylk** [comment]
For now the names of the ipynbs need to stay in sync with the legacy website unfortunately. 
The logging output is also useful so should staty.
However happy to take the first commit 	https://github.com/RaRe-Technologies/gensim/pull/1308/commits/d1492fd1ba89bafb6b77cd7ca3a20f5c0477af4a

@menshikh-iv Do you agree?

**Comment by charliejharrison** [comment]
FYI the logging output wasn't in the original

**Comment by menshikh-iv** [comment]
@tmylk I agree with you about naming, but @charliejharrison right about logging in original notebook [(proof)](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/Corpora_and_Vector_Spaces.ipynb)
I think, logging in this notebook does not contain important information (especially for novice users)

**Comment by tmylk** [comment]
@menshikh-iv lgtm https://github.com/RaRe-Technologies/gensim/pull/1308/commits/9157eec465ff7c97cc735caf961e37b71897523c

**Comment by menshikh-iv** [comment]
@charliejharrison please pull back to previous commit [9157eec](https://github.com/RaRe-Technologies/gensim/pull/1308/commits/9157eec465ff7c97cc735caf961e37b71897523c) and I will merge this PR

**Comment by charliejharrison** [comment]
Thanks, that should be done now

**Comment by charliejharrison** [comment]
Do I need to submit a new PR?

**Comment by menshikh-iv** [comment]
@charliejharrison No, I congratulate you on your first PR :+1:

**Comment by charliejharrison** [comment]
OMG thanks! 😊

**Pull request merged**
