### PR TITLE
Fix `doc2vec-lee` notebook

### PR DESCRIPTION
**Pull request by numericlee**
Remove .words from lines 613 and 617

### CODE REVIEW

**Comment by numericlee** [comment]
Without this change, code gives an error "list has no attribute .words"

**Comment by menshikh-iv** [comment]
Nice catch @numericlee! I'll merge it after release.

**Comment by menshikh-iv** [comment]
@numericlee congratz with first PR :+1:

**Comment by piskvorky** [comment]
I don't get it -- wasn't `.words` specifically added in #1841?

This PR effectively reverse that one. They can't both be right.

**Comment by menshikh-iv** [comment]
@piskvorky this fix for the mistake from #1841, `train_corpus` is `list of TaggedDocument` (in this case `.words` needed), but `test_corpus` is `list of list of str`, and here, we have no attribute `.words`.

**Pull request merged**
