### PR TITLE
Updated Annoy Tutorial with Text8

### PR DESCRIPTION
**Pull request by pmbaumgartner**
Updates:
- Runs in python 3
- Added required packages (in addition to gensim) to top of notebook
- Cleaned up some descriptive language throughout the notebook.
- Used Text8 Corpus rather than Lee corpus, since I wasn't seeing an improvement using the Lee corpus. My hypothesis is that it's too small to see any benefit from approximating. 
- Added watermark info for benchmarking comparisons
- Reorganized and restructured notebook
  - Added an outline according to the logic of the notebook
  - separated notebook cells for import, function definition, and executing code
  - Added optional logging
  - Combined num_trees performance analysis into one loop & plots into one figure and upped num_trees to 300

@tmylk

### CODE REVIEW

**Comment by tmylk** [comment]
Thanks a lot! Let's keep the old name and replace the Lee corpus ipynb with this time.

**Comment by pmbaumgartner** [comment]
Okay, should be good now, just renamed it.

**Comment by tmylk** [comment]
awesome thx

**Comment by piskvorky** [comment]
Beautiful!

**Pull request merged**
