### PR TITLE
fixed test for training (new fastText format)

### LINKED ISSUE #1370: Fasttext incorrect shape in test
I run all tests and get this error (any python version, `develop` branch)
CC @prakhar2b @jayantj 
```
======================================================================
FAIL: testTraining (gensim.test.test_fasttext_wrapper.TestFastText)
Test self.test_model successfully trained, parameters and weights correctly loaded
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ivan/release/test/gensim/gensim/test/test_fasttext_wrapper.py", line 63, in testTraining
    self.assertEqual(trained_model.wv.syn0.shape, (vocab_size, model_size))
AssertionError: Tuples differ: (1763, 10) != (1762, 10)

First differing element 0:
1763
1762

- (1763, 10)
?     ^

+ (1762, 10)
?     ^


----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by prakhar2b**
Fix #1370 
cc @menshikh-iv

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Thank you, @prakhar2b

**Comment by piskvorky** [comment]
What was the reason for this bug, what happened?

**Comment by menshikh-iv** [comment]
@piskvorky  It's ok, I speak with @prakhar2b in gitter about it.

> for the dataset that we used (lee) vocab_size in older fasttext format was 1762, but for newer format it's 1763. For loading (PR 1319), we have two separate tests (1762 for older, and 1763 for newer).`

Now, FastText saved data in new format, this was a problem of current test.

**Comment by piskvorky** [comment]
That's good to know.

Try to keep the summary / explanation on github -- the repo is followed by many people, and also indexed by google. Knowledge that's Gitter-only is lost.

**Pull request merged**
