### PR TITLE
Changed keywords.py to make imports work for python2

### PR DESCRIPTION
**Pull request by peterg17**
Changed keywords.py so that the imports work with python2, specifically for queue. Basically, just fixed this issue: http://stackoverflow.com/questions/29687837/queue-importerror-in-python-3

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks, but all tests fail with `TypeError: 'module' object is not callable`. My guess is your imports should be for a class, not module.

**Comment by tmylk** [comment]
@peterg17 Ping. Thanks for the PR. Do you plan to finish it?

**Comment by peterg17** [comment]
Hi Lev, thanks for reminding me! I think that I resolved the issue but not totally sure, i just changed the import to import from "six.moves.queue", which the file was doing before but I forgot to keep in my pull request

**Comment by gojomo** [comment]
@peterg17 – as you'll see if you're reading these comments at <https://github.com/piskvorky/gensim/pull/734>, "All checks have failed" in the automatic TravisCI build of this PR. You can click the 'Details' link to see the logs of the failures – it appears all Python 3.x builds are broken by the current code state.

**Comment by peterg17** [comment]
@gojomo Thanks for the help, I haven't used travis despite hearing a lot about it. I'm now trying to make some small tweaks to see if I can get the file to work with both Python 2/3, I just don't know what to change despite looking at the documentation for six: [https://pythonhosted.org/six/](url)

**Comment by menshikh-iv** [comment]
Ping @peterg17, what status of this PR? Will you finish it soon?

**Comment by menshikh-iv** [comment]
I close PR because it is abandoned.

**Pull request closed without merging**
