### PR TITLE
Fix Deprecation Warning

### PR DESCRIPTION
**Pull request by poornagurram**
assertequals to assertequal

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Good start @poornagurram, are you planning to continue?

**Comment by poornagurram** [comment]
Yes. I have set up things ready for this. :)

**Comment by poornagurram** [comment]
you will merge this PR or shall I do other changes too in the same PR.

**Comment by menshikh-iv** [comment]
@poornagurram please make all changes related with #1519 in current PR and ping me when you'll ready for review!

**Comment by poornagurram** [comment]
Sure!!

**Comment by poornagurram** [comment]
@menshikh-iv better now we can go for the review. As I am done with this type of warnings. Trying to explore more. will create a new pull request if I solve any.

**Comment by menshikh-iv** [comment]
@poornagurram please fix remaining `assertEquals`:
```
ivan@P50:~/release/gensim$ find gensim/ -name "*.py" | xargs grep "assertEquals"
gensim/test/test_summarization.py:        self.assertEquals(summarize(""), u"")
gensim/test/test_summarization.py:        self.assertEquals(summarize("", split=True), [])
gensim/test/test_summarization.py:        self.assertEquals(summarize_corpus([]), [])
gensim/test/test_summarization.py:        self.assertEquals(summarize_corpus(corpus), [])
gensim/test/test_summarization.py:        self.assertEquals(summarize(text), u"")
gensim/test/test_summarization.py:        self.assertEquals(summarize(text, split=True), [])
gensim/test/test_utils.py:        self.assertEquals(utils.decode_htmlentities(body), expected)
gensim/test/test_utils.py:        self.assertEquals(utils.flatten(nested_list), expected)
gensim/test/test_utils.py:        self.assertEquals(utils.flatten(not_nested), expected)
gensim/test/test_tmdiff.py:        self.assertEquals(len(annotation), self.num_topics)
gensim/test/test_tmdiff.py:        self.assertEquals(len(annotation[0]), self.num_topics)
gensim/test/test_tmdiff.py:        self.assertEquals(len(annotation), self.num_topics)
gensim/test/test_tmdiff.py:                    self.assertEquals(diff_tokens, [])
gensim/test/test_tmdiff.py:                    self.assertEquals(len(int_tokens), self.n_ann_terms)
gensim/test/test_tmdiff.py:                self.assertEquals(diff_tokens, [])
gensim/test/test_tmdiff.py:                self.assertEquals(len(int_tokens), self.n_ann_terms)
gensim/test/test_word2vec.py:        self.assertEquals(len(limited_model_kv.syn0), 3)
gensim/test/test_word2vec.py:        self.assertEquals(binary_model_kv.syn0.nbytes, half_precision_model_kv.syn0.nbytes * 2)
```

**Comment by poornagurram** [comment]
Changed all. Good to go.

**Comment by menshikh-iv** [comment]
Thanks @poornagurram, congratz with the first contribution:1st_place_medal:

**Comment by poornagurram** [comment]
@menshikh-iv woohoo!! Thank you. Looking for more.

**Pull request merged**
