### PR TITLE
Speed up Soft Cosine Measure

### PR DESCRIPTION
**Pull request by eliadl**
Use selection matrices to speed up matrix slicing.

**Motivation:**
Sometimes `softcossim` needs to be calculated O(N^2) times, e.g. for a distance matrix.

**Results:**
At least 5x speedup of `softcossim` was observed on my machine (110 µs vs 550 µs).

### CODE REVIEW

**Comment by piskvorky** [comment]
@Witiko WDYT?

**Comment by Witiko** [comment]
Looks good at first glance, but I won't be able to properly test the speed and correctness until next week. @eliadl, can you please explain the issue with the original code and what the source of the speed-up is?

**Comment by eliadl** [comment]
@Witiko I went ahead and tested with larger matrices, and the performance **decreased**.
Before, I thought that numpy's lower-level implementation would compensate for the larger complexity of matrix operations.
But that doesn't seem to be the case.

To be safe I'll close this PR, but leave the branch for you to inspect if you'd like.

Sorry and thanks for your time and review.

**Comment by eliadl** [comment]
@Witiko On second thought, perhaps it's worth considering my version only up to a certain size of the similarity matrix, as it does work faster for smaller matrices.

So the code would have an `if size > threshold else`.

Finding that `threshold` would require to profile the performance of different sizes.
Though I'm not sure different machines, OS's, python versions, etc. would have the same threshold.

**Pull request closed without merging**
