### PR TITLE
Bug Fix 1779

### PR DESCRIPTION
**Pull request by saroufimc1**
- Not sure about the header. 
- Keeping the whole embedding matrix for subwords, and only creating a dictionary for the subwords using the hashing function. In the previous version, the index was incorrectly assigned in the subword dictionary.

### CODE REVIEW

**Comment by menshikh-iv** [comment]
@manneshiva @jayantj can you look into this PR?

**Comment by manneshiva** [comment]
@saroufimc1 You might be mixing up two issues here -- #1261 and #1779. It is best to have a different PR for each of these issues. As #1261 still needs more discussion to agree upon a solution, I suggest you only address issue #1779 here -- i.e. correct the assignment of `model.wv.syn0_ngrams` after trimming of unused `ngrams` (`model.wv.syn0_ngrams.shape[0] <= self.bucket`). Also, don't forget to add a test case in `gensim/test/test_afsttext_wrapper.py` to catch this error in future.

**Comment by saroufimc1** [comment]
@manneshiva Sure, will do that. 
Thanks,
Carl

**Comment by piskvorky** [comment]
Needs a better PR title and description. 

Issue link belongs to description (Github's hyperlink), not the title.

**Comment by menshikh-iv** [comment]
ping @saroufimc1, what's status of this PR?

**Comment by menshikh-iv** [comment]
ping @saroufimc1, what's the status here?

**Comment by menshikh-iv** [comment]
I close this PR because this looks abandoned.
@saroufimc1 feel free to re-open when you continue this.

**Comment by saroufimc1** [comment]
Sorry was on vacations. Uploading my fix today. Thanks.

**Pull request closed without merging**
