### PR TITLE
LsiModel: Only log top words that actually exist in the dictionary

### LINKED ISSUE #3090: KeyError in LsiModel constructor
#### Problem description

Hi, I'm trying to use an `LsiModel` to reduce a corpus.  When constructing the `LsiModel`, I sometimes see `KeyError`s raised by logging code (specifically, [here](https://github.com/RaRe-Technologies/gensim/blob/f8110c036f30e030e4c27101398e076cd1254819/gensim/models/lsimodel.py#L673) via [here](https://github.com/RaRe-Technologies/gensim/blob/f8110c036f30e030e4c27101398e076cd1254819/gensim/models/lsimodel.py#L522)).  If I manually remove that logging, I can generate the model without errors.

I found [a similar issue](https://github.com/RaRe-Technologies/gensim/issues/1995), where @menshikh-iv recommended "removing gaps" from my dictionary.  I definitely could do that, but it would require an extra pass over my input, which can be pretty large.  Instead, it would be trivial to do a more safe lookup into `id2word` than using `[val]`.  For example, this workaround fixes my problem:

```diff
diff --git i/gensim/models/lsimodel.py w/gensim/models/lsimodel.py
index 97cc921f..4b703dcf 100644
--- i/gensim/models/lsimodel.py
+++ w/gensim/models/lsimodel.py
@@ -670,7 +670,7 @@ class LsiModel(interfaces.TransformationABC, basemodel.BaseTopicModel):
         c = np.asarray(self.projection.u.T[topicno, :]).flatten()
         norm = np.sqrt(np.sum(np.dot(c, c)))
         most = matutils.argsort(np.abs(c), topn, reverse=True)
-        return [(self.id2word[val], 1.0 * c[val] / norm) for val in most]
+        return [(self.id2word.get(val, "<None>"), 1.0 * c[val] / norm) for val in most]
 
     def show_topics(self, num_topics=-1, num_words=10, log=False, formatted=True):
         """Get the most significant topics.
```

#### Steps/code/corpus to reproduce

```python
>>> from gensim.models import LsiModel
>>>
>>> tfidf = [[(0, 0.0), (1, 1.0), (2, 2.0)]]
>>> id2word = {0: "a", 1: "b", 2: "c", 100: "d"}  # note that there is a gap here!
>>> LsiModel(tfidf, id2word=id2word)
Traceback (most recent call last):
  File "gensim_test.py", line 5, in <module>
    LsiModel(tfidf, id2word=id2word)
  File "/path/to/gensim/models/lsimodel.py", line 445, in __init__
    self.add_documents(corpus)
  File "/path/to/gensim/models/lsimodel.py", line 518, in add_documents
    self.print_topics(5)
  File "/path/to/gensim/models/basemodel.py", line 36, in print_topics
    return self.show_topics(num_topics=num_topics, num_words=num_words, log=True)
  File "/path/to/gensim/models/lsimodel.py", line 699, in show_topics
    topic = self.print_topic(i, topn=num_words)
  File "/path/to/gensim/models/basemodel.py", line 18, in print_topic
    return ' + '.join('%.3f*"%s"' % (v, k) for k, v in self.show_topic(topicno, topn))
  File "/path/to/gensim/models/lsimodel.py", line 669, in show_topic
    return [(self.id2word[val], 1.0 * c[val] / norm) for val in most]
  File "/path/to/gensim/models/lsimodel.py", line 669, in <listcomp>
    return [(self.id2word[val], 1.0 * c[val] / norm) for val in most]
KeyError: 69
```

#### Versions

Please provide the output of:

```python
>>> import platform; print(platform.platform())
>>> import sys; print("Python", sys.version)
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
>>> import numpy; print("NumPy", numpy.__version__)
>>> import scipy; print("SciPy", scipy.__version__)
>>> import gensim; print("gensim", gensim.__version__)
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
Linux-5.4.0-64-generic-x86_64-with-debian-buster-sid
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0]
Bits 64
NumPy 1.19.1
SciPy 1.5.3
gensim 3.8.3
FAST_VERSION 0
```

### PR DESCRIPTION
**Pull request by kmurphy4**
In some pathological cases, we might try to log the top N words, even
though we haven't seen N words yet.  In these cases, we can just exit
the loop early.

Closes #3090.

### CODE REVIEW

**Comment by kmurphy4** [comment]
@piskvorky should I add any documentation or test cases?

**Comment by piskvorky** [comment]
Thanks! Maybe add a code comment that links to https://github.com/RaRe-Technologies/gensim/issues/3090.

So that future people reading the code are not confused or don't accidentally delete that code, thinking it's useless.

**Comment by kmurphy4** [comment]
Ok, force-pushed a comment.  Thanks for being so responsive :smile:

**Review by piskvorky — APPROVED** [review]

**Comment by kmurphy4** [comment]
@piskvorky anything else you need from me here? No rush, just trying to make sure it doesn't get lost in the shuffle :smile:

**Comment by piskvorky** [comment]
Thanks, a reminder is definitely a good idea :)

PR already approved by me; the next step is a review by @mpenkov. Who will merge if all OK.

**Comment by mpenkov** [comment]
Looks good to me! Thank you @kmurphy4 !

**Comment by kmurphy4** [comment]
Thank you!

**Pull request merged**
