### PR TITLE
Optimize performance of Author-Topic model

### PR DESCRIPTION
**Pull request by horpto**

### CODE REVIEW

**Comment by jonaschn** [comment]
@horpto Is there any performance gain? Did you benchmark this change?

**Comment by horpto** [comment]
@jonaschn well, i can make a some microbench with a few days.

**Review by piskvorky — APPROVED** [review]

**Comment by mpenkov** [comment]
@horpto Are you able to share the benchmark results?

**Review by mpenkov — APPROVED** [review]
Benchmark results would have been good, but the change makes sense, so the absence of the benchmarks shouldn't block this PR.

**Comment by mpenkov** [comment]
Thank you @horpto for your contribution.

**Pull request merged**
