### PR TITLE
Fix overflow error for `*Vec` corpusfile-based training

### PR DESCRIPTION
**Pull request by persiyanov**
Fix for https://github.com/RaRe-Technologies/gensim/issues/2578

Previous fix (https://github.com/RaRe-Technologies/gensim/pull/2239/files) solved the problem for datasets that have number of `words` exceeding max int. However, there were some users who used far bigger datasets which exceeded max int even in terms of `examples`.

### CODE REVIEW

**Comment by persiyanov** [comment]
cc @piskvorky @mpenkov Sorry for the delay guys, I was bogged down with other stuff. But the fix for https://github.com/RaRe-Technologies/gensim/issues/2578 is finally here :)

**Comment by mpenkov** [comment]
@persiyanov Thank you for looking into this. Can you investigate why the AppVeyor tests are failing?

**Comment by persiyanov** [comment]
@mpenkov For python 3.5, the error is ` ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject`

For python 3.6, there are other runtime errors like `_configtest.obj : error LNK2001: unresolved external symbol acosl`.

I presume it is related to how I generated new C/C++ files with cython. I used python 3.7.4 and usual cython command like `cython --cplus gensim/models/fasttext_corpusfile.pyx`. As of now, what is the most proper way to regenerate C/C++ files? I think that command worked few years ago.

**Comment by mpenkov** [comment]
I expect #2706 to fix this.

**Comment by mpenkov** [comment]
@persiyanov Please merge gensim/develop into your branch to fix the appveyor issues.

**Comment by persiyanov** [comment]
@mpenkov Done!

**Comment by gojomo** [comment]
This shouldn't have added the `*.cpp` files into git, should it? (They should be fully deterministic byproducts of the `.pyx` files, and our builds/releases had been working for quite a while without any `.cpp`/`.c` files from developers' individual builds in the source tree.) @persiyanov @mpenkov

**Pull request merged**
