### PR TITLE
Resolving issue #908

### PR DESCRIPTION
**Pull request by saksham15082**

### CODE REVIEW

**Comment by saksham15082** [comment]
@tmylk  pls guide me further as i am quite new to github and have just started on open source.Thanks for the patience.

**Comment by tmylk** [comment]
Hi @saksham15082 Welcome and thank you for your contribution.
Please see comments in the identical PR https://github.com/RaRe-Technologies/gensim/pull/923
Also @markroxor was thinking of working on it. Please coordinate with him so that there is no duplication of effort.

**Comment by saksham15082** [comment]
@markroxor  please tell me on what you want to work so that there are no duplications.

**Comment by markroxor** [comment]
I won't mind taking this one but am involved with other issues as well. Your call @saksham15082 if you would like to take it further. Please go ahead. :)

**Comment by piskvorky** [comment]
@saksham15082 please provide some context and links in the PR description. What is this about?

**Comment by tmylk** [comment]
Almost done in https://github.com/RaRe-Technologies/gensim/pull/978

**Pull request closed without merging**
