### PR TITLE
Add testfixtures in test_require

### PR DESCRIPTION
**Pull request by sara-02**

### CODE REVIEW

**Comment by tmylk** [comment]
@sara-02 Thanks a lot for the PR!

**Comment by sara-02** [comment]
@tmylk  Welcome.

**Comment by piskvorky** [comment]
What is this about? Why is this needed?

Can you provide some context in the PR description?

**Comment by sara-02** [comment]
@piskvorky I have added the description, hope that helps.

**Comment by piskvorky** [comment]
Thanks Sara.

@tmylk I still don't get it -- since when do we depend on an external test library?

**Comment by tmylk** [comment]
@piskvorky  It is only a test-level dependency to [check](https://github.com/RaRe-Technologies/gensim/blob/b6e9570c3d5b6b2cf80e175e0c705405b045ca44/gensim/test/test_word2vec.py#L492) the right warning appears in the log

**Comment by piskvorky** [comment]
I see, thanks.

**Pull request merged**
