### PR TITLE
[WIP] Doc2vec on proteins example in iPython notebook

### PR DESCRIPTION
**Pull request by ziky90**
**Do not merge yet!**

This PR is a draft of simple example how to use doc2vec on proteins. This aims to solve https://github.com/piskvorky/gensim/issues/645

**TODO:**
- [ ] Run whole iPython notebook on some smaller dataset.

### CODE REVIEW

**Comment by tmylk** [comment]
Ping @ziky90

**Comment by ziky90** [comment]
@tmylk I still haven't made it to generate smaller example dataset for Doc2Vec on proteins. Could the PR still stay open (possibly for bioinformaticians to play with or to finish)?

**Comment by parulsethi** [comment]
@ziky90 This is a really nice addition! I'm interested in completing this PR

As this notebook will only be for demo purposes, and accuracy of the results don't matter much, so I guess we can simply use a subset of sequences in fasta file already used in notebook, rather than whole proteome (with explicit mention of taking this approach).
It would still convey the idea of using doc2vec on protein sequences

**Comment by menshikh-iv** [comment]
Ping @ziky90, what status of this PR? Will you finish it soon?

**Comment by menshikh-iv** [comment]
I close PR because it is abandoned.

**Pull request closed without merging**
