### PR TITLE
Ensures FastText returns consistent dtypes

### LINKED ISSUE #1637: FastText wrapper returns inconsistent dtypes
#### Description
`gensim.models.wrappers.FastText` returns inconsistent dtypes.

#### Steps/Code/Corpus to Reproduce
```python
from gensim.models.wrappers import FastText
embeds = FastText.load_fasttext_format(...)
```
For an existing word:
```python
embeds['the'].dtype == dtype('float32')
```
For an "imputed" word (missing from the vocabulary). The word embedding is computed as the sum of embedding for n-grams:

```python
embeds['ttttt'].dtype == dtype('float64')
```

The problem in `models/wrappers/fasttext.py::FastTextKeyedVectors.word_vec`. In the case of a missing word, the zero vector is initialised to be a 64-bit float array to which a bunch of 32-bit embeddings are added to. 

#### Versions
Linux-4.4.0-97-generic-x86_64-with-Ubuntu-16.04-xenial
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609]
NumPy 1.13.3
SciPy 0.19.1
gensim 3.0.1
FAST_VERSION 1

### PR DESCRIPTION
**Pull request by mcobzarenco**
Fix #1637

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Please add test for fasttext (check that now all types is consistent)

**Comment by mcobzarenco** [comment]
Cool! Will do.

**Comment by menshikh-iv** [comment]
Ping @mcobzarenco, how is going?

**Comment by mcobzarenco** [comment]
Sorry for delay -- I now added a simple test to check that the dtypes are the same.

**Comment by menshikh-iv** [comment]
Thanks @mcobzarenco

**Pull request merged**
