### PR TITLE
Fix bug in bm25.py

### PR DESCRIPTION
**Pull request by souravsingh**
Related to #1718

### CODE REVIEW

**Comment by piskvorky** [comment]
That looks like a serious / critical bug, thanks!

What functionality affected? How did this bug manifest itself in practice?

**Comment by souravsingh** [comment]
Nothing is mentioned in the issue itself. The person filing the issue just mentions that it is a bug, and didn't say anything about how it affects the functionality.

**Comment by piskvorky** [comment]
Probably best to double check and verify.

**Comment by souravsingh** [comment]
The person who filed the issue mentioned the following- 

> Actually, I used the bm25 module independently of the
summarization module just for IR.

> Basically, I wanted to quickly compare bm25 with tf-idf, pylucene's api
seemed to be too cumbersome, and I did not want to reinvent the wheel.
Gensim generally has pretty good coding standards that's why I decided to
use bm25 from gensim instead of the various other BM25 implementations on
github. But after implementation I noticed that the results from bm25 were
worse than standard tf-idf and that's why I looked at the code in more
detail. The data that I am working on comes from [https://www.ldc.upenn.edu
](LDC) so its hard to share it.

**Comment by piskvorky** [comment]
Yeah, I saw.

It's better link to @se4u's [answer](https://github.com/RaRe-Technologies/gensim/issues/1718#issuecomment-345463764), instead of copy-pasting.

**Comment by souravsingh** [comment]
So we confirm the behavior of the bug by running both tf-idf and bm25 correct? It might be a bit difficult since bm25 doesn't have any docstrings to help in understanding the behavior.

**Comment by menshikh-iv** [comment]
BM25 formula:
image
Current variant (in code) looks correct.

**Comment by eliotpbrenner** [comment]
Can you please double check?  I believe it should be `len(self.corpus[index])`, not `len(document)`
Thanks!

**Comment by se4u** [comment]
@eliotpbrenner yes you are right !

**Comment by menshikh-iv** [comment]
@eliotpbrenner https://github.com/RaRe-Technologies/gensim/commit/24a692b2f1160ff699f65ac26fc840d115d17155#commitcomment-26708993

**Pull request merged**
