### PR TITLE
Fastsent

### PR DESCRIPTION
**Pull request by fh295**
Added fastsent model. 

Fastsent is described in Learning Distributed Representations of Sentences from Unlabelled Data by Felix Hill, Kyunghyun Cho and Anna Korhonen (http://arxiv.org/abs/1602.03483). 

The model considers three consecutive sentences from the training data in turn. For each such triple, the input (syn0) embeddings of the words in the middle sentence are summed (or averaged). This sentence representation is used for to predict output (syn1) embeddings of each word in the adjacent (previous and following) sentences. 

This implementation adapts the CBOW model from word2vec. The two (summed) external windows of words in the CBOW architecture function like words from the middle sentence in fastsent. The inner target word in CBOW functions like each of the words in the two outer sentences in fastsent.

### CODE REVIEW

**Comment by piskvorky** [comment]
Wow, interesting! Thanks @fh295 

@gojomo @tmylk can you help review?

**Comment by tmylk** [comment]
@fh295 New features need to be unit tested.
See [word2vec unit tests](
https://github.com/piskvorky/gensim/blob/develop/gensim/test/test_word2vec.py) for an example

**Comment by fh295** [comment]
I had a go at making the unit tests...on my branch two of the tests are failed but it's the same two that are failed with train_word2vec.py so I assume that's OK?

**Comment by fh295** [comment]
Hello Lev,
Did you see the unit tests that I added? Does it look OK?
Sorry, if I've made errors. Not really a software developer!
Felix

On 20 February 2016 at 21:39, Lev Konstantinovskiy <notifications@github.com
> wrote:

> @fh295 <https://github.com/fh295> New features need to be unit tested.
> See word2vec unit tests
> <https://github.com/piskvorky/gensim/blob/develop/gensim/test/test_word2vec.py>
> for an example
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/piskvorky/gensim/pull/612#issuecomment-186684389>.
>



-- 

Felix Hill
University of Cambridge
fh295@cam.ac.uk

http://www.cl.cam.ac.uk/~fh295/

**Comment by tmylk** [comment]
Hey @gojomo what do you think about this PR?

**Comment by gojomo** [comment]
I like the algorithm: that this training variant using neighboring sentences (but still otherwise 'shallow') gets such useful sentence vectors. Especially if it dominates other range-of-text vectors for some important applications, it could be a nice option for gensim. 

But the level of cut & paste code duplication is a concern – it's harder to review/understand the key changes, and if there are fixes/improvements in the original code it will be extra effort to keep this variant in sync. I'd feel better if it were some smaller specialization – perhaps by subclassing/overriding or some configurable context/target policy that drops-in to the main implementations. But that might require some deep/fancy refactoring. (I have a hunch such a refactoring might point to some other interesting new hybrid training modes – new mixes of skips & averages & concatenations & contexts – but I'm unsure who might ever get to that.)

This feature might live best as a separate fork/PR, with a pointer from the main project – unless either (a) there's a growing demand for the algorithm; or (b) it can be a neat & small option, an example of incremental customization.

**Comment by zachmayer** [comment]
I keep getting `UserWarning: C extension not loaded for FastSent, training will be slow. Install a C compiler and reinstall gensim for fast training.` when I try to run fastsent.FastSent with this branch checked out.

I have a c compiler, I installed gensim from source, and I don't get this error when I run Word2Vec.

Is there something special I need to do to compile fastset, other than run `setup.py install`?

**Comment by zachmayer** [comment]
I tried running `python setup.py clean --all` and then `python setup.py install --force`, but I still get that warning.

**Comment by fh295** [comment]
Hey chaps, I'm not a software developer and to be honest my coding in
Cython is pretty awful - if I made a mistake I'm sorry. Lev recommended
that I should make a PR, I just suggested that you might like to add these
models. But I'm a researcher, and if they are not up to your standards then
I apologise. I'd love you to have them as part of your package, but it's
not what I'm paid to do, so I don't have the time to learn how to do it
well myself I'm afraid....

On 18 March 2016 at 20:21, Zach Mayer <notifications@github.com> wrote:

> I tried running python setup.py clean --all and then python setup.py
> install --force, but I still get that warning.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/piskvorky/gensim/pull/612#issuecomment-198527349>
>



-- 

Felix Hill
University of Cambridge
fh295@cam.ac.uk

http://www.cl.cam.ac.uk/~fh295/

**Comment by zachmayer** [comment]
I checked out your branch, rebased on master, and built one of the required cythonzied files: https://github.com/zachmayer/gensim

It now compiles and installs everything correctly when you `python setup.py install`.  I think this is super useful code and should be a part of gensim.

**Comment by zachmayer** [comment]
Id be happy to make another PR, based on my rebase.

**Comment by fh295** [comment]
Hi Zach,
Thanks for helping - for me, it would be great if you made another PR - so
if others agree just go ahead.
Best, Felix

On 18 March 2016 at 23:03, Zach Mayer <notifications@github.com> wrote:

> Id be happy to make another PR, based on my rebase.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/piskvorky/gensim/pull/612#issuecomment-198572823>
>



-- 

Felix Hill
University of Cambridge
fh295@cam.ac.uk

http://www.cl.cam.ac.uk/~fh295/

**Comment by zachmayer** [comment]
@fh295 @gojomo @tmylk @piskvorky see new PR here: https://github.com/piskvorky/gensim/pull/630

**Comment by tmylk** [comment]
Updated PR in #630

**Comment by hocnv90** [comment]
> Added fastsent model.
> 
> Fastsent is described in Learning Distributed Representations of Sentences from Unlabelled Data by Felix Hill, Kyunghyun Cho and Anna Korhonen (http://arxiv.org/abs/1602.03483).
> 
> The model considers three consecutive sentences from the training data in turn. For each such triple, the input (syn0) embeddings of the words in the middle sentence are summed (or averaged). This sentence representation is used for to predict output (syn1) embeddings of each word in the adjacent (previous and following) sentences.
> 
> This implementation adapts the CBOW model from word2vec. The two (summed) external windows of words in the CBOW architecture function like words from the middle sentence in fastsent. The inner target word in CBOW functions like each of the words in the two outer sentences in fastsent.

Maybe it like Skip-gram?

**Pull request closed without merging**
