### PR TITLE
adding Pyro4.expose

### PR DESCRIPTION
**Pull request by markroxor**
in regard to issue #807

### CODE REVIEW

**Comment by markroxor** [comment]
Someone please confirm the fix on his machine.

**Comment by tmylk** [comment]
Did it work for you when you followed the Gensim Distributed tutorial?

**Comment by markroxor** [comment]
It fixes the error 
`RuntimeError: failed to initialize distributed LSI (remote object doesn't expose any methods or attributes. Did you forget setting @expose on them?)`

 but another error

 `SerializeError: unsupported serialized class: gensim.corpora.dictionary.Dictionary` 
pops up. Trying to figure it out.

**Comment by markroxor** [comment]
I've created `/tmp/deerwester.dict` and `/tmp/deerwester.mm` from the tutorial [here.](https://radimrehurek.com/gensim/tut1.html#from-strings-to-vectors)

**Comment by markroxor** [comment]
Turns out that this error doesn't appear for Pyro==4.22 but for the newer Pyro==4.47 in accordance with [this](https://groups.google.com/d/msg/gensim/eXNEDxyQnwU/fcv47Upbu3wJ). Should I file an issue?

**Comment by tmylk** [comment]
@markroxor Thanks for working on this. We need to support the latest version of Pyro 4.47h, no need to support older versions. I will merge it now as it is needed.
Tests are still peniding though.

**Comment by markroxor** [comment]
@tmylk  The error `SerializeError: unsupported serialized class: gensim.corpora.dictionary.Dictionary` still appears for Pyro 4.47 therefore I cant work on issue #911  . As per the google discussion [here.](https://groups.google.com/forum/#!msg/gensim/eXNEDxyQnwU/hv2V9N0MYAoJ) 

> The latest Pyro version supports more serialization formats... which is exactly what was causing the problems :)

**Comment by markroxor** [comment]
okay you raised an issue.

**Pull request merged**
