### PR TITLE
Fix integer overflow during `FastText` training with `corpus_file`

### PR DESCRIPTION
**Pull request by irinade**
(#2258)

* replace `int` by `long long`

### CODE REVIEW

**Comment by mpenkov** [comment]
Thank you for the PR.

@menshikh-iv I think there is an outstanding PR here that covers more cases: https://github.com/RaRe-Technologies/gensim/pull/2239. I think we should merge that PR in favor of this one. Thoughts?

**Comment by irinade** [comment]
Hello !
Do you have an idea of what causes the errors ? Is it linked to the modification proposed ?

**Comment by mpenkov** [comment]
@irinade The build errors on CircleCI look unrelated.

The modification itself looks good, but we already have a PR (#2239) that covers the particular problem and many potential others.

**Comment by menshikh-iv** [comment]
@irinade thanks for PR, error really unrelated, I'm on it in https://github.com/RaRe-Technologies/gensim/tree/fix-build

I agree with @mpenkov, we should accept "wider" PR #2239, which overlaps the current, anyway, thanks for contribution :+1:

**Pull request closed without merging**
