### PR TITLE
[WIP] Website for gensim powered by github pages

### PR DESCRIPTION
**Pull request by markroxor**
The preview of the github pages can be seen here at [markroxor.github.io/gensim/](http://markroxor.github.io/gensim/)

### CODE REVIEW

**Comment by markroxor** [comment]
The showroom page is the main highlight - https://markroxor.github.io/gensim/showroom/index.html

**Comment by souravsingh** [comment]
@markroxor The showrooms look really well made. But there is an issue with the showroom.

On clicking on a showroom example, I am not able to exit the example display(Seems trivial in terms of fix).
 Just curious, Did you lift the design from the Shogun Website repo?

**Comment by tmylk** [comment]
Thanks for the pr! Is it possible to disable image scaling? The Gensim logo looks strange stretched on a mobile

**Comment by markroxor** [comment]
@souravsingh You need to press `Esc` to exit it and yes.
@tmylk I have changed the default image.

**Comment by tmylk** [comment]
Thanks for the website. It looks great!

1) Please bring back notebook titles. They appear in [shogun showroom](http://www.shogun-toolbox.org/showroom) but not in gensim

2) [tutorials](https://markroxor.github.io/tutorials) should link to [this page](https://github.com/RaRe-Technologies/gensim/blob/develop/tutorials.md) converted to html. it should be part of the website so that google can index it

3) the ipynb notebooks should stay in `docs/notebooks`. feel free to put the converted htmt files wherever you need.

**Comment by markroxor** [comment]
@tmylk I have taken care of all the four points.
It is just that the links in the apiref are not functional.

**Comment by tmylk** [comment]
Current status: this is a great prototype. A designer will look at it over next 2 months.

**Comment by markroxor** [comment]
@menshikh-iv The web-view is almost ready. Is there any thing else left to tweak?

**Comment by menshikh-iv** [comment]
@markroxor thanks, we'll think about it.

Now we have 2 variants (how to replace old):
- Your site version
- New skin for Sphinx (rdt, alabaster, etc)

Your site looks better than templates, but it's more complicated for support for our side. We'll try different variants (I hope in this year) and I'll notify you of our decision.

In any case, many thanks for your work @markroxor, sorry that it happened so.

**Comment by menshikh-iv** [comment]
We thought, tested and decided that we'll use one of the templates for Sphinx.
Despite this, thanks again @markroxor.

**Pull request closed without merging**
