### PR TITLE
Added topic coherence rst files

### PR DESCRIPTION
**Pull request by dsquareindia**
Referring to issue #905. @tmylk just a small addition here.

### CODE REVIEW

**Comment by dsquareindia** [comment]
I'll add the topic coherence dir as well here.

**Comment by dsquareindia** [comment]
@tmylk ready for merge.

**Comment by tmylk** [comment]
Thanks for taking this on! Did you check that html files appear after running the commands in https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#documentation?

**Comment by dsquareindia** [comment]
oh getting an error there:
```
Exception occurred:
  File "/home/devashish/EXPERIMENTATION/gensim/docs/src/./gensim_theme/genindex.html", line 49, in block "body"
    {%- for entryname, (links, subitems, _) in column %}
ValueError: need more than 2 values to unpack
The full traceback has been saved in /tmp/sphinx-err-eVoHAI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:34: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by dsquareindia** [comment]
updated to Sphinx 1.4 and now it builds fine. Sorry for the noise!

**Comment by tmylk** [comment]
Thanks for the PR!

**Comment by dsquareindia** [comment]
No problem! The topic coherence docs look hideous currently. Will improve on that soon.

**Pull request merged**
