### PR TITLE
Store images from README directly in repository. Fix #1849

### LINKED ISSUE #1849: Store images from README directly in repository
**Problem**: We have [adopters table](https://github.com/RaRe-Technologies/gensim#adopters) that contains concrete companies with logo & additional information. Images (logo) stored everywhere (random CDN, sites, etc) -> can be broken (unavailable) -> README doesn't looks good.

**Solution**: Store all images in repository

**Warning**: We don't want to store large `.jpg`, all images should be optimized before.

### PR DESCRIPTION
**Pull request by ibrahimsharaf**
Issue (https://github.com/RaRe-Technologies/gensim/issues/1849)

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Thank you @ibrahimsharaf, can you make it bigger (same size as https://github.com/RaRe-Technologies/gensim#adopters)?

**Comment by ibrahimsharaf** [comment]
Hi @menshikh-iv, I already made them all `width=100`, should I make it 200?

**Comment by menshikh-iv** [comment]
@ibrahimsharaf I see two problems:
- Look at the rendered version of `README.md`, this doesn't look like `width=100` (you can check it with "devtools" of your browser)
- You have distorted the proportions of some of the logos, need to stay original proportions.

**Comment by menshikh-iv** [comment]
Ping @ibrahimsharaf, how is going?

**Comment by ibrahimsharaf** [comment]
Hi @menshikh-iv, I've been busy recently, will continue work on the PR by tomorrow.

**Comment by ibrahimsharaf** [comment]
Hi @menshikh-iv, would you take a look?

**Comment by menshikh-iv** [comment]
Hi @ibrahimsharaf, thanks, good work:+1:

**Pull request merged**
