### PR TITLE
fix broken link in documentation

### LINKED ISSUE #3144: Fix documentation link to mycorpus.txt download
#### Problem description

Trying to reproduce Corpora and Vector Space tutorial given in the documentation, but the link to download txt file is not working. The link given in the tutorial [here](https://radimrehurek.com/gensim/auto_examples/core/run_corpora_and_vector_spaces.html#corpus-streaming-one-document-at-a-time) is giving 404 error.

#### Steps/code/corpus to reproduce

Just visit this [link](https://radimrehurek.com/gensim/mycorpus.txt) which is used in the code given in the documentation, it is not working.

### PR DESCRIPTION
**Pull request by rohit901**
fixes #3144﻿

### CODE REVIEW

**Comment by mpenkov** [comment]
Are you able to update the gallery files, as described in https://radimrehurek.com/gensim/auto_examples/howtos/run_doc.html#finalizing-your-contribution?

**Comment by rohit901** [comment]
Hey, I tried to do that now and I'm getting this error, could you please check this.
`make: Entering directory '/home/rohit/Documents/Gensim/gensim/docs/src'
sphinx-build -b html -d _build/doctrees  -W . _build/html
Running Sphinx v3.2.1
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for auto_examples/core... [100%] run_similarity_queries.py                                                
generating gallery for auto_examples/tutorials... [100%] run_wmd.py                                                          
generating gallery for auto_examples/howtos... [100%] run_compare_lda.py                                                     
computation time summary:
    - gallery/core/run_core_concepts.py:                0.00 sec   0.0 MB
    - gallery/core/run_corpora_and_vector_spaces.py:    0.00 sec   0.0 MB
    - gallery/core/run_similarity_queries.py:           0.00 sec   0.0 MB
    - gallery/core/run_topics_and_transformations.py:   0.00 sec   0.0 MB
    - gallery/howtos/run_compare_lda.py:                0.00 sec   0.0 MB
    - gallery/howtos/run_doc.py:                        0.00 sec   0.0 MB
    - gallery/howtos/run_doc2vec_imdb.py:               0.00 sec   0.0 MB
    - gallery/howtos/run_downloader_api.py:             0.00 sec   0.0 MB
    - gallery/tutorials/run_annoy.py:                   0.00 sec   0.0 MB
    - gallery/tutorials/run_doc2vec_lee.py:             0.00 sec   0.0 MB
    - gallery/tutorials/run_fasttext.py:                0.00 sec   0.0 MB
    - gallery/tutorials/run_lda.py:                     0.00 sec   0.0 MB
    - gallery/tutorials/run_scm.py:                     0.00 sec   0.0 MB
    - gallery/tutorials/run_wmd.py:                     0.00 sec   0.0 MB
    - gallery/tutorials/run_word2vec.py:                0.00 sec   0.0 MB
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 97 source files that are out of date
updating environment: [new config] 97 added, 0 changed, 0 removed
Your CPU supports instructions that this binary was not compiled to use: SSE3 SSE4.1 SSE4.2 AVX AVX2                         
For maximum performance, you can install NMSLIB from sources 
pip install --no-binary :all: nmslib
reading sources... [100%] wiki                                                                                               
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] wiki                                                                                                

Warning, treated as error:
/home/rohit/Documents/Gensim/gensim/docs/src/distributed.rst:59:term worker not found in case sensitive match.made a reference to Worker instead.
make: *** [Makefile:37: html] Error 2
make: Leaving directory '/home/rohit/Documents/Gensim/gensim/docs/src'
`

**Comment by mpenkov** [comment]
OK, leave it with us. Thank you for your contribution!

**Comment by piskvorky** [comment]
@mpenkov I fixed the title (caps + was too cryptic). Updating the CHANGELOG in one place makes such fixes are easier for me, to do in one focused batch.

**Pull request merged**
