### PR TITLE
[MRG] Clean up evaluate_word_pairs code

### LINKED ISSUE #3315: evaluate_word_pairs gives ValueError: x and y must have length at least 2.
#### Problem description

I am trying to run an evaluation on a pair of trained vectors on a datafile, namely [this one](https://github.com/tca19/near-lossless-binarization/blob/master/datasets/MEN.txt). However, when using the function `wordembeddingmodel.evaluate_word_pairs(datapath("MEN.txt"))` (it is stored in the datapath folder) I get the error `ValueError: x and y must have length at least 2.`. I suspect this has to do with the formatting, but I cannot figure out what the issue is. 

#### Steps/code/corpus to reproduce

Traceback: 

```bash
File "/.../src/evaluate.py", line 25, in evaluate_wordsimilarity
    ] = wordembeddingmodel.evaluate_word_pairs(datapath(worddataset))[0][0]
  File "/home/users/filip/.conda/envs/sskgnn/lib/python3.9/site-packages/gensim/models/keyedvectors.py", line 1321, in evaluate_word_pairs
    pearson = stats.pearsonr(similarity_gold, similarity_model)
  File "/home/users/filip/.conda/envs/sskgnn/lib/python3.9/site-packages/scipy/stats/stats.py", line 4016, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.
```
Dataset: Downloaded from [here](https://raw.githubusercontent.com/tca19/near-lossless-binarization/master/datasets/MEN.txt). I download it and create it using: 

```python3
import requests
from gensim.test.utils import datapath
import os.path as osp

fpath = datapath("")
file = "https://raw.githubusercontent.com/tca19/near-lossless-binarization/master/datasets/MEN.txt"
r = requests.get(file)
filename = file.split("/")[-1]
with open(osp.join(fpath,filename), "wb") as f:
    f.write(r.text.encode("utf-8").strip())
```

```python
>>> print(wordembeddingmodel.lifecycle_events)
*** AttributeError: 'Word2VecKeyedVectors' object has no attribute 'lifecycle_events'
```

#### Versions

Please provide the output of:

```python
>>> import platform; print(platform.platform())
ec.FAST_VERSION)Linux-5.4.0-90-generic-x86_64-with-glibc2.31
>>> import sys; print("Python", sys.version)
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0]
>>> import struct; print("Bits", 8 * struct.calcsize("P"))
Bits 64
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.21.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.7.1
>>> import gensim; print("gensim", gensim.__version__)
gensim 3.8.3
>>> from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
FAST_VERSION 1
```

Any help is greatly appreciated! Thank you :)

Cheers
Filip

### PR DESCRIPTION
**Pull request by piskvorky**
Fixes #3315.

The code was brittle and failed to check and report on user input properly.

### CODE REVIEW

**Comment by piskvorky** [comment]
@mpenkov CI fail seems unrelated. Can you please check?

**Comment by piskvorky** [comment]
CI is green now, I don't really understand what happened. Anyway, merging!

**Comment by mpenkov** [comment]
It's green because I re-ran the failed part only.

Sometimes the tests can fail because of a network error installing packages.  In that case, re-running the test usually solves the problem. You can re-run by going for the test that failed and selecting "re-run failed jobs" from the widget in the top right corner of the screen.

**Comment by piskvorky** [comment]
Interesting. So a problem on Microsoft's side?

"Just restart it" follows like a time honoured tradition then :)

**Pull request merged**
