### PR TITLE
Inherit LDAMallet wrapper from BaseModel to standardise print_topics

### PR DESCRIPTION
**Pull request by tmylk**
Continuing from #946

### CODE REVIEW

**Comment by tmylk** [comment]
Appveyor and osx builds are broken by this merge.
"cannot import unittests2"
Please skip the tests with [skiptest](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_dtm.py#L33) instead of using unittest2

**Comment by piskvorky** [comment]
@tmylk you are the only participant in this issue -- who are you talking to?

**Comment by markroxor** [comment]
@piskvorky it is addressed to me.

**Comment by markroxor** [comment]
@tmylk shouldn't we add `pip install unittests2` to the build config file instead of skipping?

**Pull request merged**
