### PR TITLE
Fix Numpy deprecation warning in matutils.corpus2dense

### PR DESCRIPTION
**Pull request by PeteBleackley**
Fix for issue #2432. This is a one line change (generator to list comprehension)

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks @PeteBleackley . That doesn't look like a 1-line change though, and there are conflicts.

Can you rebase your changes on top of current `develop` branch?

**Comment by PeteBleackley** [comment]
@piskvorky It should be a one line change. For some reason git has included all the commits from my previous 2 PRs (it lives up to its name). I had tried to make sure that I was synced to the latest version of the develop branch before making my changes as well. I'll have to try again.

**Comment by piskvorky** [comment]
You could also start from gensim's `develop` directly, by doing a hard reset: `git reset --hard gensim/develop`. And after that, re-apply your one-liner.

That way, there's no risk your "local" `develop` branch already diverged from upstream `develop`.

**Comment by mpenkov** [comment]
@PeteBleackley Are you able to rebase?

**Comment by mpenkov** [comment]
This has already been fixed as part of #2371

**Pull request closed without merging**
