### PR TITLE
Add "downloads" badge to README

### PR DESCRIPTION
**Pull request by piskvorky**
Trying the idea from https://github.com/RaRe-Technologies/smart_open/issues/440.

#### Motivation

In general, seeing how much others use a package improves confidence in its robustness and maintenance. A kind of social proof.

I see no downsides, except if the service that provides this badge (https://pepy.tech/) proves unstable or unreliable.

Badges for gitter and wheels seem useless, so I removed them.

#### Checklist

Before you create the PR, please make sure you have:

- [x] Picked a concise, informative and complete title
- [x] Clearly explained the motivation behind the PR
- [x] Linked to any existing issues that your PR will be solving
- [x] Included tests for any new functionality
- [x] Checked that all unit tests pass

### CODE REVIEW

**Comment by piskvorky** [comment]
@mpenkov unrelated, but the "build" badge on the main page is red now, failing.

**Comment by piskvorky** [comment]
I'm also considering removing "Anaconda Cloud"; WDYT?

**Comment by piskvorky** [comment]
@mpenkov ready to merge! CC @gojomo @menshikh-iv do you see anything else vital enough to be communicated in a badge on top of the README?

**Comment by gojomo** [comment]
If you wanted to drive more usage/support-traffic to Gitter, I could see that badge making sense, but not sure that's a goal. 

If you wanted to more generally show affiliations with, or usages of, many other projects/tech as a sort of broad-community-spirit signal, I could see adding more - but probably at a separate section at the bottom, or else they'd dilute the importance/usefulness of the top few. Not important though.

**Comment by piskvorky** [comment]
Gensim's Gitter is a ghost town. At least I never go there… I wonder if anyone does.

**Comment by menshikh-iv** [comment]
Looks fine

> I'm also considering removing the "Anaconda Cloud" badge; WDYT?

Not sure than this needed, many persons use them, but up to you.

> It's still crowded up there, and this one seems near-useless (and out of our control).

Not true, we control them via https://github.com/conda-forge/gensim-feedstock/pull/43


BTW don't forget to merge the latest `develop` to your branch (before merging PR), looks like you branched from an old (broken) commit

**Comment by piskvorky** [comment]
Thanks for the heads up – `develop` merged.

**Pull request merged**
