### PR TITLE
Add word embedding viz to word2vec notebook. Fix #1419

### LINKED ISSUE #1419: Word Embedding Visualizer
Currently, there is no direct way to visualise word embeddings made by the gensim word2vec model.
I have made a visualiser using matplotlib.
It uses Incremental PCA to reduce to manageable dimensions and then uses tSNE to bring it down to 2 dimensions.

Note: I have taken some of my code from https://github.com/jeffThompson/Word2VecAndTsne

This will be my first contribution (if at all), so please guide me.

(Also, I am not sure if this is the right place to submit a feature request, so please don't mind)

### PR DESCRIPTION
**Pull request by markroxor**
Extending #1440.
Addressing issue #1419

### CODE REVIEW

**Comment by menshikh-iv** [comment]
@markroxor please run viz code too (viz should be already rendered in notebook)

**Comment by markroxor** [comment]
It is already rendered I made sure of that. Can you pull it and try? I can see it locally but not on github. Possibly because it is using `pyplot`.

**Comment by halflings** [comment]
Sorry if this is redundant with a comment on the original issue, but I really think you should consider integrating with the tf embedding projector:

http://projector.tensorflow.org/

**Comment by menshikh-iv** [comment]
@halflings answered https://github.com/RaRe-Technologies/gensim/issues/1419#issuecomment-353279319

**Comment by menshikh-iv** [comment]
@markroxor please disable logging only for one cell (not for all notebook)

**Comment by menshikh-iv** [comment]
Thank you @markroxor :+1:

**Pull request merged**
