### PR TITLE
replacing deleted notebooks with placeholders

### PR DESCRIPTION
**Pull request by mpenkov**
#2591 ported some Jupyter notebooks to Sphinx gallery and then removed them. That turned out to be undesirable because it left many broken links that we cannot control via our Web server.

This PR replaces the previously removed notebooks with a placeholder document that points to the new location.

### CODE REVIEW

**Comment by piskvorky** [comment]
Looks good, except some of these tutorials were *removed*, rather than *moved*. So people won't find them at that new suggested location.

**Comment by qinpeiming** [comment]
good

**Comment by gojomo** [comment]
While better than a 404-not-found, I was hoping for placeholders that point directly to the analogous new tutorial, where there is one. (If there isn't one, because the old tutorial was so bad it's better deleted, then a 404 might be fine. I'm not sure which ones have been deleted-without-an-equivalent-replacement.)

**Comment by mpenkov** [comment]
OK. I'm going to merge this in the interest of our users, and come back to tweaking things later (probably around next week or so).

**Comment by rice-cake** [comment]
in Similarity Queries notebook:

sims = sorted(enumerate(sims), key=lambda item: -item[1])
for i, s in enumerate(sims): print(s, documents[i]) <-- incorrect

for s in sims: print(s, documents[s[0]]) <-- correct

**Pull request merged**
