### PR TITLE
adding wordsim240.tsv wordsim296.tsv wordsim297.tsv

### PR DESCRIPTION
**Pull request by TankAbraham**
Adding common used Chinese Word Similarity evaluating dataset to the repo those are wordsim240, wordsim296 and wordsim297.

### CODE REVIEW

**Comment by piskvorky** [comment]
@TankAbraham what's the motivation for this? Do you intend to use those datasets in unit tests? (good idea)

Or in documentation/tutorials? What is this for?

**Comment by TankAbraham** [comment]
Motivation:
Nowadays, more and more Chinese users apply our toolkit in their researching.
In the research domain of Chinese word embedding, we have to evaluate our models on the dataset of wordsim-240, 296, 297.

A2: Sure, I have to use it, that's why I contribute to the repo.

A3: Sorry, I didn`t update the documentation/tutorials.

A4: As I wrote, this is the commonly used Chinese Word Similarity evaluating dataset.

**Comment by TankAbraham** [comment]
Sorry I didn't follow the instruction of "How to submit an issue?". What should I do next?

**Comment by piskvorky** [comment]
@TankAbraham you should expand the PR to make it useful:

1. Use this dataset in unit tests, so it's a) clear how to use it b) we guard against future regressions.
2. Use this dataset in a tutorial / docstring, so users know it exists and how to use it.

**Comment by TankAbraham** [comment]
@piskvorky 
Ok, sir, I'll try it. Thank you!
I'm a beginner of  GitHub and word embedding researching domain.

**Comment by mpenkov** [comment]
@TankAbraham Do you plan to finish this PR? It needs a significant amount more effort in order for us to be able to accept it. At this stage, I think it's best to close the PR instead of proceeding. Please let us know if you intend to continue working on this.

**Pull request closed without merging**
