### PR TITLE
Fix URL in doc string

### PR DESCRIPTION
**Pull request by jonaschn**
The [API docs](https://radimrehurek.com/gensim/models/ldaseqmodel.html) were not displayed correctly.
image

### CODE REVIEW

**Review by piskvorky — APPROVED** [review]
Thanks!

**Comment by jonaschn** [comment]
@piskvorky @mpenkov By accident I force-pushed an old local `patch-2` branch used for #3082 (that was already deleted on my github fork).
Now I figured out how to undo it and force-pushed again (the correct changes).

**Comment by piskvorky** [comment]
Thanks :)

**Review by mpenkov — APPROVED** [review]

**Comment by mpenkov** [comment]
Thank you @jonaschn !

**Pull request merged**
