### PR TITLE
Small bugfix for semantic similarity evaluation

### PR DESCRIPTION
**Pull request by akutuzov**
Handling of non-Latin OOV pairs logging in evaluate_word_pairs function (they were not converted to UTF-8, which caused logger to fail).

### CODE REVIEW

**Comment by tmylk** [comment]
Please ignore Python 2.6 and Python 3.3 build errors. They are due to latest PyEMD [update](https://github.com/wmayner/pyemd/commit/e3bf5a7757854a43e0030a5d89b73fa1a1845fb4#commitcomment-20393940)

**Comment by akutuzov** [comment]
Fixed.

**Comment by piskvorky** [comment]
This doesn't look right. What "OOV pairs"? `pairs` is a filename (bad variable name, but that's a separate issue).

What exactly fails and how?

**Comment by tmylk** [comment]
@akutuzov Python 2.6 and 3.3 failures should be fixed now.

**Comment by akutuzov** [comment]
@piskvorky The problem arises when we have non-Latin word pairs in the dataset, and they are absent in the model. The logger prints these pairs on debug level [here](https://github.com/RaRe-Technologies/gensim/pull/1079/files#diff-741f69634ff2e1b2c4ce544e0d82a1e6R544), and it fails in Python 2. To fix it, I explicitly state that the whole string is Unicode. For Python 3 it's irrelevant, as far as I can see.
The _pairs_ variable indeed is the path to the dataset file (I agree that's not the best variable name). The logger [outputs](https://github.com/RaRe-Technologies/gensim/pull/1079/files#diff-741f69634ff2e1b2c4ce544e0d82a1e6R535) this path in case there are incorrect lines in the dataset. Again, in this PR I explicitly state that this warning is Unicode, to handle rare cases when the path contains non-Latin characters.

**Comment by piskvorky** [comment]
Ah, I see what you mean -- you're talking about non-ASCII (not non-Latin) characters in `line`, which is a unicode string.

I'm not very familiar with the `.format` fancy formatting, but normal `"%s"` should output them (upcast to unicode) just fine.

I'd prefer the fix to use lazy argument formatting: `logger.info("%s", unicode_string)`. It's easier to read and clearer (and doesn't fail).

Independently: why `pairs` (the filesystem path) was being converted with `.encode('utf8')` I don't know. Unless there's an explicit comment that documents this (and there isn't), I'd consider it a bug.

**Comment by piskvorky** [comment]
@tmylk please review before merging...

**Comment by tmylk** [comment]
Reviewed and tested simple formatting

**Comment by piskvorky** [comment]
@akutuzov can you please fix the comments above?

**Comment by tmylk** [comment]
@akutuzov In particular @piskvorky is referring to lazy formatting.

Lazy: `logger.info("%s", unicode_string).`

Eager: `logger.info("%s" % unicode_string).`

**Comment by akutuzov** [comment]
Fixed in #1084

**Pull request merged**
