### PR TITLE
fixing input

### PR DESCRIPTION
**Pull request by tebandesade**
I was getting a TypeError: can't concat bytes to str 
because of this line self.wv.syn0[i] = self.seeded_vector(self.wv.index2word[i] + str(self.seed))
and the input was b"''"

### CODE REVIEW

**Comment by gojomo** [comment]
The test failure is in exactly the line changed... so unless there's a case the the test should be changed, this (seemingly harmless) fix is breaking previously-working behavior.

**Comment by menshikh-iv** [comment]
@gojomo @tebandesade what's status here? Should I close this PR?

**Comment by gojomo** [comment]
I don't know the bug this is supposed to fix, *and* the code breaks an existing test. So without more details/fixes it should be set aside.

**Comment by menshikh-iv** [comment]
Thanks @gojomo 
@tebandesade can you describe more concretely what's a motivation of this fix (describe concrete bug)?

**Comment by menshikh-iv** [comment]
I close this pull request because it looks abandoned

**Pull request closed without merging**
