### PR TITLE
Fix smart_open deprecation warning in index loading

### PR DESCRIPTION
**Pull request by itayB**

### CODE REVIEW

**Comment by itayB** [comment]
Fixing this log:
`/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function`

**Comment by piskvorky** [comment]
Related to https://github.com/RaRe-Technologies/smart_open/issues/319#issuecomment-502035045

**Comment by itayB** [comment]
@piskvorky updated the PR

**Comment by piskvorky** [comment]
Thanks @itayB . LGTM, once @mpenkov reviews.

**Comment by mpenkov** [comment]
Are there any other places we're using smart_open? It's hard for me to believe it's only in one file. I'd check myself but I'm currently on the road.

**Comment by itayB** [comment]
@mpenkov there was a misunderstanding, I fixed it only for the indexer. It appears in a lot of other areas, I don't mind to fix them as well.

**Comment by mpenkov** [comment]
Yes, could you please go ahead and apply these changes to everywhere in gensim? I think it makes more sense to handle this all at once than piecemeal.

**Comment by itayB** [comment]
Should I close this one? https://github.com/RaRe-Technologies/gensim/pull/2530 covers it as well..

**Comment by Medinaaz** [comment]
https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function

**Pull request closed without merging**
