### PR TITLE
Added datasets

### PR DESCRIPTION
**Pull request by bhargavvader**
@tmylk , this is with regard to #857.

I've added the datasets - it is around 2 mb, which I do not think is too big. 
Would this be fine?

### CODE REVIEW

**Comment by tmylk** [comment]
Just make sure they are excluded from the package in manifest.in but still run in travis ipynb checks...

**Comment by bhargavvader** [comment]
How exactly do I check for that?

**Comment by tmylk** [comment]
You need to exclude them in manifest.in but still see the tests of ipynb being run in travis logs

**Comment by bhargavvader** [comment]
Cool, done!

**Comment by tmylk** [comment]
Does this ipynb now run in travis? Can it be seen in travis log?

**Pull request merged**
