### PR TITLE
Fix aarch64 wheels

### PR DESCRIPTION
**Pull request by tbbharaj**
This PR addresses the issue to build aarch64 wheels.
Travis build for Python 3.9 is failing because it couldn't find matching scipy distribution == 1.5.3. This issue is being addressed in this PR.

If there are any questions/comments - I'd be happy fix things as needed.

Thank you
Tanveen

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks! Shouldn't these versions match `setup.py` though?  I forgot what exactly needs to be updated where… @mpenkov could you please summarize the way we update dependencies across different files / subsystems in [Gensimi & Compatibility](https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility)

**Comment by tbbharaj** [comment]
> Thanks! Shouldn't these versions match `setup.py` though?
> 
> I forgot what exactly needs to be updated where, so everything's in sync… @mpenkov could you please summarize the way we update dependencies across the different files / subsystems in [Gensimi & Compatibility](https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility)

Thank you @piskvorky for reviewing my PR.
[setup.py](https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L328) defines `'scipy >= 0.18.1'`, this should be okay with existing changes in PR isn't?

Also `scipy==1.5.3` doesn't have build for [Python 3.9](https://pypi.org/project/scipy/1.5.3/#files), therefore for Python 3.6 scipy is configured as `scipy==1.5.3` and [1.7.0 ](https://pypi.org/project/scipy/1.7.0/#files)for others which is latest

**Comment by tbbharaj** [comment]
> Thanks! Shouldn't these versions match `setup.py` though?
> 
> I forgot what exactly needs to be updated where, so everything's in sync… @mpenkov could you please summarize the way we update dependencies across the different files / subsystems in [Gensim & Compatibility](https://github.com/RaRe-Technologies/gensim/wiki/Gensim-And-Compatibility).

Updated scipy version in `setup.py`. Hope that looks good to you

**Comment by mpenkov** [comment]
Thank you for your work @tbbharaj. I'm closing this PR in favor of #3219. I based it on your changes, minus the setup.py changes which are not needed here (we're in the middle of a release).

**Pull request closed without merging**
