### PR TITLE
Add tox environments to setup.cfg, fix napoleon import

### PR DESCRIPTION
**Pull request by sezanzeb**
- `tox -e compile,docs` fails with `ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found` otherwise on my machine. `tox -e ALL` can be used now
- fixed napoleon import `Could not import extension sphinxcontrib.napoleon (exception: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py))` https://github.com/sphinx-doc/sphinx/issues/10378#issuecomment-1107455569

Python 3.10.6, 5.15.65-1-MANJARO

### CODE REVIEW

**Comment by sezanzeb** [comment]
Can you please extend the instructions in the wiki (https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#documentation) to

```bash
pip install ".[docs]"
tox -e compile,docs  # generate new docs version, will be available in docs/src/_build/html
cd docs/src
make upload  # upload new docs to site (need ssh permissions)
```

?

**Comment by mpenkov** [comment]
From memory, we stopped using tox a long time ago. If some instructions refer to it, then the instructions are out of date.

The steps to build the docs are simpler without tox:

    pip install ".[docs]"
    make -C docs/src html

**Comment by sezanzeb** [comment]
ah, yeah it's mentioned in the wiki https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#documentation

**Comment by mpenkov** [comment]
Yeah, you should be able to just edit the wiki directly

**Comment by piskvorky** [comment]
By the way, CI is red = failing build. I'm not aware of any merges or changes that could have caused this. @mpenkov is this some infrastructure problem outside of Gensim?

**Comment by mpenkov** [comment]
Yeah, one of the windows tests failed because of a HTTP issue downloading one of our data files.

https://github.com/RaRe-Technologies/gensim/actions/runs/3169051969/jobs/5160694925

```
    def http_error_default(self, req, fp, code, msg, hdrs):
>       raise HTTPError(req.full_url, code, msg, hdrs, fp)
E       urllib.error.HTTPError: HTTP Error 503: Egress is over the account limit.
```

**Comment by piskvorky** [comment]
@mpenkov ping let's finish this before the next bug fix release.

**Comment by mpenkov** [comment]
> Can you please extend the instructions in the wiki

OK, updated: https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#documentation

**Pull request merged**
