### PR TITLE
[MRG] Updates to poincare notebooks

### PR DESCRIPTION
**Pull request by jayantj**
Makes the following updates to the tutorial notebook - 

1. Removes minute technical details and evaluation results
2. Adds links to detailed blog post and other useful links

Evaluation notebook - 
1. Adds results for regularized models
2. HTML tables instead of ascii-tables to easily publish in blogs.

### CODE REVIEW

**Comment by janpom** [comment]
This looks good. One minor thing: The "Dimensions" label is off in the results table. It should span all the dimension columns and shouldn't span the "Metric" column.

**Comment by menshikh-iv** [comment]
@jayantj 
- "Note that not all the above libraries are part of the gensim dependencies, so they might need to be installed separately. These requirements are listed in the poincare requirements.txt" - please add cell with `pip install ...` line instead (this file already does not exist)
- This is the second rename `evaluation` -> `tutorial` -> `evaluation`, please explain what is happening

**Comment by jayantj** [comment]
@menshikh-iv do you mean I should hardcode the pip installs in the notebook itself?

**Comment by menshikh-iv** [comment]
@jayantj yes, this is simpler and easy-to-edit if needed.

**Pull request merged**
