### PR TITLE
Documentation for Montemurro and Zanette algorithm

### PR DESCRIPTION
**Pull request by PeteBleackley**
Added the Montemurro and Zanette algorithm to the API docs

### CODE REVIEW

**Comment by PeteBleackley** [comment]
Just realised this has already been done.

**Comment by piskvorky** [comment]
Oh, has it? How is that possible?

**Comment by PeteBleackley** [comment]
It seems to have been done in https://github.com/RaRe-Technologies/gensim/pull/1709

**Comment by piskvorky** [comment]
Aha. Is there anything here that is not there?

In other words, could we take the best of both PRs?

**Comment by PeteBleackley** [comment]
I don't think there's anything in this one that isn't in #1709

**Pull request closed without merging**
