### PR TITLE
Implement the Google Tag Manager (TGM)

### PR DESCRIPTION
**Pull request by yardos**
- removed old Google Analytics code (Urchin)
- added code for Google Tag Manager - one in head, the other in body

... continued from #1554 .

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Congratz with your first PR @yardos:+1:

**Comment by piskvorky** [comment]
@yardos do you want me to regenerate http://radimrehurek.com/dostal_gensim/ again? Or is this enough.

The main gensim page will be regenerated with the next release (~next week IIRC, @menshikh-iv ?).

**Comment by yardos** [comment]
@piskvorky yes, please regenerate http://radimrehurek.com/dostal_gensim/  - I can test the GTM implementation there at the mean time

**Comment by menshikh-iv** [comment]
@piskvorky ~next 2 weeks I think.

**Comment by piskvorky** [comment]
@yardos there were no new changes, so http://radimrehurek.com/dostal_gensim/  should be up-to-date.

**Pull request merged**
