### PR TITLE
PR for supervised Topic models

### PR DESCRIPTION
**Pull request by souravsingh**
@menshikh-iv The PR is a continuation of #1608 

Tests need to be added for this to work.

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Hey @souravsingh, what's status here? I don't see updates for notebook, "apply" method, benchmark, tests, etc.

**Comment by menshikh-iv** [comment]
@souravsingh are you plan to finish this or should I close PR?

**Comment by souravsingh** [comment]
@menshikh-iv I plan on finishing this.

**Comment by menshikh-iv** [comment]
@souravsingh FYI - if this will be abandoned (inactive), I'll close it.

**Comment by souravsingh** [comment]
Sure. I currently am far away from my laptop. Once I come back, I should be able to complete the work.

**Comment by menshikh-iv** [comment]
ping @souravsingh, what's about your plans?

**Comment by souravsingh** [comment]
I will be closing this for now, and work on finishing it in future.

**Pull request closed without merging**
