### PR TITLE
Use gensim.test.utils datapath() to construct paths to the test data

### PR DESCRIPTION
**Pull request by pabs3**
Makes the code more readable and consistent with other tests.

### CODE REVIEW

**Review by piskvorky — APPROVED** [review]
Thanks so much!

**Comment by pabs3** [comment]
Fixed the flake8 complaint by dropping the `os.path` import.

**Review by piskvorky — APPROVED** [review]
I love these little clean ups and tidying up, much appreciated @pabs3 !

**Comment by piskvorky** [comment]
Merged. Thank you!

**Pull request merged**
