### PR TITLE
Point WordEmbeddingSimilarityIndex documentation to gensim.similarities

### PR DESCRIPTION
**Pull request by Witiko**
Currently, all documentation, Jupyter notebooks and code examples assume that `WordEmbeddingSimilarityIndex` is located in `gensim.models`, although it lives in `gensim.similarities` since 4.0.0. This pull request fixes the documentation.

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks @Witiko ! The main place for documentation of the [gallery](https://radimrehurek.com/gensim/auto_examples/index.html#documentation). I fear the `notebooks` directory is hard to discover, and not really maintained / tested.

Would it make sense to convert this into a gallery Tutorial/Howto script? With notebook / html auto-generated from the converted source, [instructions](https://radimrehurek.com/gensim/auto_examples/howtos/run_doc.html#sphx-glr-auto-examples-howtos-run-doc-py).

**Comment by Witiko** [comment]
@piskvorky I love the idea behind the gallery. I don't have the time to convert the tutorial at the moment, but I will take a look during the next week.

**Comment by piskvorky** [comment]
@Witiko we're planning the 4.0 release now. Can you please finish this? Thanks.

**Comment by Witiko** [comment]
@piskvorky Thanks for the reminder. I was not really working on this, but the conversion from notebook to gallery sound interesting and I can give it a go over the weekend.

**Comment by Witiko** [comment]
@piskvorky Would it be OK to merge [the SCM notebook](https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/soft_cosine_tutorial.ipynb) with [the WMD autoexample](https://radimrehurek.com/gensim/auto_examples/tutorials/run_wmd.html)? I think we could get rid of a lot of duplication and have a single sly example for word-embedding-based document similarity measures.

**Comment by piskvorky** [comment]
Anything that cleans up & simplifies documentation is highly desirable. @mpenkov WDYT?

**Comment by mpenkov** [comment]
No objections from me.

**Comment by Witiko** [comment]
In the end, the preprocessing pipeline is quite different for the SCM and the WMD, so I kept the tutorials separate for now for simplicity. I added some fixes for the WMD, though, such as removing a section about deprecated `init_sims` method, and redirecting the documentation to the Gallery. This PR should be good to merge.

**Comment by piskvorky** [comment]
Thanks so much @Witiko . Is the failing test related?

**Comment by Witiko** [comment]
@piskvorky Not really, the failing test is for Doc2Vec, which this PR does not touch.

**Comment by mpenkov** [comment]
I re-ran the tests, they all passed.

**Comment by mpenkov** [comment]
Merged, thank you @Witiko !

**Pull request merged**
