### PR TITLE
Make most_similar accept topn of any integer type

### LINKED ISSUE #2496: SparseTermSimilarityMatrix - TypeError: 'numpy.float32' object is not iterable
I am using gensim 3.7.3 and python3.6.

I am following the exact example of SoftCosineSimilarity at https://radimrehurek.com/gensim/similarities/docsim.html
but with my own dataset and embeddings trained on Fasttext.
Dictionary and WordEmbeddingSimilarityIndex are executed properly but then I get an error when trying SparseTermSimilarityMatrix. I found a similar issue, that was solved in the pull below, but I still seem to get this error. However, I tried the exact same code with Word2Vec and the gensim imported common_texts and it worked. Why it doesnt work in my case, is it related to FastText?

https://github.com/RaRe-Technologies/gensim/pull/2356

My code:
```
from gensim.models import FastText
from gensim.corpora import Dictionary
from gensim.models import WordEmbeddingSimilarityIndex
from gensim.similarities import SoftCosineSimilarity, SparseTermSimilarityMatrix

model = FastText.load('fasttext_vector_100')
# this line works
model.wv.most_similar(positive=['test'], topn=2)
termsim_index = WordEmbeddingSimilarityIndex(model.wv)
# texts is similar to common_texts, list of lists of strings
dictionary = Dictionary(texts)
bow_corpus = [dictionary.doc2bow(document) for document in texts]
# it fails here
similarity_matrix = SparseTermSimilarityMatrix(termsim_index, dictionary)
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-129-c33cf3beaa3e> in <module>()
----> 1 similarity_matrix = SparseTermSimilarityMatrix(termsim_index, dictionary)  # construct similarity matrix

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\similarities\termsim.py in __init__(self, source, dictionary, tfidf, symmetric, positive_definite, nonzero_limit, dtype)
    232             most_similar = [
    233                 (dictionary.token2id[term], similarity)
--> 234                 for term, similarity in index.most_similar(t1, num_rows)
    235                 if term in dictionary.token2id]
    236 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\similarities\termsim.py in <listcomp>(.0)
    231             num_rows = nonzero_limit - num_nonzero
    232             most_similar = [
--> 233                 (dictionary.token2id[term], similarity)
    234                 for term, similarity in index.most_similar(t1, num_rows)
    235                 if term in dictionary.token2id]

~\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\models\keyedvectors.py in most_similar(self, t1, topn)
   1418         else:
   1419             most_similar = self.keyedvectors.most_similar(positive=[t1], topn=topn, **self.kwargs)
-> 1420             for t2, similarity in most_similar:
   1421                 if similarity > self.threshold:
   1422                     yield (t2, similarity**self.exponent)

TypeError: 'numpy.float32' object is not iterable

```

### PR DESCRIPTION
**Pull request by Witiko**
This PR continues #2356 and #2461 and closes #2496. The PR makes the following changes:
- d910fa9: This change is unrelated to #2496, but it fixes one implementation of `most_similar` ([`PoincareKeyedVectors`](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/poincare.py#L822)) that I missed in #2461.
- b34b06e: This change closes #2496 by allowing any subtype of [`numbers.Integral`](https://docs.python.org/2.7/library/numbers.html#numbers.Integral) to be accepted as the parameter `topn` in `most_similar`. This change also adds a unit test.
- b588bd7: This change is an additional defensive fix of #2496 that patches the caller of `most_similar` not to use `topn=0`. This is because there are many implementations of `most_similar` and expecting all the current and future implementations to uphold the contract seems naive.
- 83455e2: This change makes the variable notation of the [`SparseTermSimilarityMatrix`](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/similarities/termsim.py#L184) consistent and prevents a possible integer overflow.

### CODE REVIEW

**Comment by Witiko** [comment]
The AppVeyor build seems broken.

**Comment by Witiko** [comment]
I tried to force-push a couple of times, but the AppVeynor build seems to be consistently failing to install dependencies.

**Comment by piskvorky** [comment]
Ping @mpenkov – can you assist Vitek with the CI (AppVeyor) problems?

**Comment by mpenkov** [comment]
Looks like appveyor is failing to install numpy:

```
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy<2.0.0,>=1.9.0')
```

@menshikh-iv Any idea why that could be?

**Comment by menshikh-iv** [comment]
@mpenkov 

Thanks to `pyemd` https://github.com/wmayner/pyemd/blob/develop/setup.py#L95
I recommend do not install it on windows with python 2 (just avoid this problem, if we are lucky, related tests will be skip).

**Comment by piskvorky** [comment]
@mpenkov I don't think it means anything for us. We're not using any functionality from the newer NumPy releases. That `pyemd` dependency is marginal, we could drop it altogether if it gives us trouble.

In other words, we can continue to *require* a fairly old version of NumPy (which supports py2). But users are free to install newer versions of NumPy too — we don't care.

**Comment by Witiko** [comment]
Note that if we drop the `pyemd` dependency, [12 tests](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_similarities.py#L35) will be skipped.

**Comment by Witiko** [comment]
I removed pyemd from `win_testenv` in setup.py, but this does not appear to solve the issue. The culprit could be `numpy`, `scipy`, or any of the packages in `.[test-win]`, i.e. in `win_testenv`:

``` ini
deps =
    py37: numpy==1.14.5
    py37: scipy==1.1.0

    py27: numpy==1.11.3
    py27: scipy==0.18.1
    py35: numpy==1.11.3
    py35: scipy==0.18.1
    py36: numpy==1.11.3
    py36: scipy==0.18.1

    linux: .[test]
    win: .[test-win]
```
``` python
    extras_require={
        'distributed': distributed_env,
        'test-win': win_testenv,
```
``` python
win_testenv = [
    'pytest',
    'pytest-rerunfailures',
    'mock',
    'cython',
    'testfixtures',
    'scikit-learn',
    'Morfessor==2.0.2a4',
    'python-Levenshtein >= 0.10.2',
    'visdom >= 0.1.8, != 0.1.8.7',
]
```

**Comment by menshikh-iv** [comment]
So, now the issue with scikit-learn, because they don't support python2 more
Possible solutions
- use an older version of scikit-learn for windows
- get rid sklearn from python2+win
- get rid python2 support from gensim

**Comment by Witiko** [comment]
I can see both `numpy==1.11.3` and `scipy==0.18.1` for Python 2.7 at the [`--find-links` website used by ](http://28daf2247a33ed269873-7b1aad3fab3cc330e1fd9d109892382a.r6.cf2.rackcdn.com/).

**Comment by Witiko** [comment]
I reverted the `pyemd` removal, so that we can solve this general issue separately.

**Comment by mpenkov** [comment]
@menshikh-iv I'm +1 for removing Py2 support. We could do this in the next major release.

If people are keen to continue using Py2, then that's fine, they can keep using gensim 3.x. @piskvorky WDYT?

**Comment by piskvorky** [comment]
Yes, next major release (4.x) is OK. No clear release date nor milestones for 4.x though, so this is theoretical for now. Getting Gensim into a better shape is more important (like `pyemd`, `sklearn` is largely irrelevant to Gensim; we do need `numpy` though).

Sorry for hijacking your PR @Witiko :)

**Comment by Witiko** [comment]
I don't mind, dropping the Python 2 support is an interesting topic. Please, let me know if I can help, or when I can rerun the tests for this PR.

**Comment by mpenkov** [comment]
@piskvorky @Witiko I fixed the AppVeyor problems. Is this ready to merge?

**Comment by Witiko** [comment]
@mpenov Great work! I will update the documentation and ping you.

**Comment by Witiko** [comment]
@mpenov Great work! Yes, this PR should be ready to merge.

**Comment by Witiko** [comment]
@mpenkov Great work! Yes, this PR should be ready to merge.

**Comment by piskvorky** [comment]
@mpenkov ping. After fixing `smart_open`, perhaps we can make a bugfix release?

**Comment by mpenkov** [comment]
OK, merged. @Witiko Thank you for your contribution and your patience.

@piskvorky What do you think about the scope of this change? This seems to be new functionality: does it warrant a minor version bump?

**Comment by piskvorky** [comment]
Looking at the PR description: this looks like a textbook bug fix.

Which part do you see as substantial?

**Comment by mpenkov** [comment]
I think I got it mixed up with another PR. We'll treat this as a bugfix.

**Pull request merged**
