### PR TITLE
Release 4.0.0beta

### PR DESCRIPTION
**Pull request by mpenkov**
We normally merge release branches onto master locally, using the git CLI, but there were some conflicts, and I thought it prudent to deal with them in a separate PR, where we can comment and discuss, etc.

The conflicts are caused by the non-standard way that we handled the previous release (3.8.3). Unlike regular releases, that branch off develop, the 3.8.3 release branched off the 3.8.2 tag on master (?) - the first commit was afaf76f7aa0659c600a3a4a369aeab6652ad8c69. This branch is still around: https://github.com/RaRe-Technologies/gensim/compare/release-3.8.3.

The sole purpose of 3.8.3 was to temporarily bring back Py2.7 support to gensim (we removed it prematurely in 3.8.2). All work done on the 3.8.3 branch was related to Py2.7, so it was never merged to develop or master. Regular work continued during the release, and we did merge develop into the release-3.8.3 branch (see c3d95ab9b95058c2d496fa280fdec50c0511dd5d).

Shortly after the release of 3.8.3, people pointed out that it was missing from the change log on the develop branch. While this was expected for us, because we never merged release-3.8.3 into develop (see above for reason), it was confusing for people. So, we updated the develop changelog to mention 3.8.3. This is the PR here: #2831 .

I couldn't work out what the cause of the conflicts was, but there were only a small number of them:

```
  (use "git add <file>..." to mark resolution)
        both modified:   CHANGELOG.md
        both modified:   docs/src/conf.py
        both modified:   setup.py
        both modified:   tox.ini
```

I resolved them in favor of the release branch. You can check that the differences between release-4.0.0beta and develop are minimal, so there are no merge artifacts in those conflicted files:

```
gensim) sergeyich:gensim misha$ git diff upstream/develop upstream/release-4.0.0beta --minimal -- CHANGELOG.md docs/src/conf.py setup.py tox.ini | cat
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 067a361c..7108bd15 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,7 +1,7 @@
 Changes
 =======

-## 4.0.0beta, FIXME 2020-10-??
+## 4.0.0beta, 2020-10-31

 **⚠️ Gensim 4.0 contains breaking API changes! See the [Migration guide](https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4) to update your existing Gensim 3.x code and models.**

diff --git a/docs/src/conf.py b/docs/src/conf.py
index 13d26e25..ba4973d0 100644
--- a/docs/src/conf.py
+++ b/docs/src/conf.py
@@ -61,9 +61,9 @@ copyright = u'2009-now'
 # built documents.
 #
 # The short X.Y version.
-version = '4.0'
+version = '4.0.0beta'
 # The full version, including alpha/beta/rc tags.
-release = '4.0.0.dev0'
+release = '4.0.0beta'

 # The language for content autogenerated by Sphinx. Refer to documentation
 # for a list of supported languages.
diff --git a/setup.py b/setup.py
index 6c09eaf6..b3a2b61c 100644
--- a/setup.py
+++ b/setup.py
@@ -344,7 +344,7 @@ if need_cython():

 setup(
     name='gensim',
-    version='4.0.0.dev0',
+    version='4.0.0beta',
     description='Python framework for fast Vector Space Modelling',
     long_description=LONG_DESCRIPTION,

(gensim) sergeyich:gensim misha$
```

I think we're ready to proceed, so:

1. Merge this PR into master
2. Tag master
3. Merge master into develop
4. etc.

### CODE REVIEW

**Comment by piskvorky** [comment]
OK, that `git diff develop release-4.0.0beta` makes me easier.

What's the "merge artifact" in 3918704cea7e04b1f59aaeb710fc3f3a45699b1c though?

**Comment by mpenkov** [comment]
> OK, that `git diff develop release-4.0.0beta` makes me feel easier. LGTR.
> 
> What's the "merge artifact" in [3918704](https://github.com/RaRe-Technologies/gensim/commit/3918704cea7e04b1f59aaeb710fc3f3a45699b1c) though?

I'm not 100% sure. I resolved the merge conflicts manually, and then ran a diff to check that I got them all right, and that artifact came out. The lines themselves come from `master`:

https://github.com/RaRe-Technologies/gensim/blame/8b1ea6a07a2d6010d4af6d2491f6cb008fa1e01a/setup.py#L348

**Comment by piskvorky** [comment]
If I understand correctly, git added two `install_requires` sections on merge, without reporting any conflict?

Scary, but the diff is definitely answer. So as long as the diff is fine, please release. I'll switch the website symlink right after + tweet. Thanks.

**Review by piskvorky — APPROVED** [review]

**Comment by gojomo** [comment]
In my opinion, this was done exactly backwards, and has resulted in a seriously messed-up project `develop` history. 

The commit labeled "Release 4.0.0beta" has an unhelpful title & gigantic commit message & reports as touching 500+ files. 

`develop` was what was tested, `develop` was what had attention. Any release should be the smallest-possible 'just the release housekeeping' commit, to build the artifacts, then return the `develop` to dev-status.

This process was something else, more complicated, hader to review and understand, for unclear benefits. Anything that was in the weird orphaned -3.8.3 branch should have been forgotten as a one-time error, not carried forward to confuse things for 4.0.0-beta. 

Cleanly releasing off `develop` is an important enough goal that if it were up to me I'd undo this & ensure the release is clear & minimal off of the `develop` trunk.

(I can't tell if the current state of `develop` is mid-release or post-release. It appears the tree as of the big commit titles "Release 4.0.0beta" reports its own version as "4.0.0.dev0". Then there's another commit - post-beta? Or something else? It's generically and unhelpfully titled "Merge remote-tracking branch 'upstream/master' into develop"? **That** commit changes the self-reported version to "4.0.0beta" - which in my views should only ever appear on trunk in the arbitrarily-small time it takes to mint an exact release, then be changed to `dev` again before any other time/changes/work could accumulate.)

**Comment by piskvorky** [comment]
Mid-release, as far as I can tell. @mpenkov is fighting with the CI wheels I guess, which is a mid-release step that fails randomly and can take several hours.

The step of changing the self-reported version in `develop` comes after that. [Docs](https://github.com/RaRe-Technologies/gensim/wiki/Developer-page#make-a-new-release-for-maintainers).

I already switched the website because I expected the release to be done by now. @mpenkov what the ETA?

Re. branches: yes, 3.8.2 was a botched up release, which led to another messed up release 3.8.3, which affects 4.0.0 now again. Ditching the orphaned branch was my choice too but apparently since `git diff` showed no significant changes, merging that branch is actually cleaner – the full history is now in git.

**Comment by mpenkov** [comment]
We're still mid-release. There's a number of unforeseen issues blocking the wheel builds. It's hard for me to give an ETA because I haven't encountered these issues before, and my bandwidth during the working week is limited.

The problems I can see include:

- numpy.testing.decorators missing in the Appveyor (Win) builds
- x86_64-linux-gnu-gcc: error: unrecognized command line option '-std=c++14' during Linux builds
- AttributeError: module 'numpy.random' has no attribute 'default_rng' during MacOS builds
- ImportError: cannot import name 'FAST_VERSION' from 'gensim.models.fasttext' (/Users/travis/build/RaRe-Technologies/gensim-wheels/venv/lib/python3.8/site-packages/gensim/models/fasttext.py) during MacOS Py3.8 build

The way to proceed is, for each issue:

1. Investigate the cause
2. Fix the cause in gensim-wheels repo
3. Push to gensim-wheels master, wait for rebuild

If either of your are able to handle any of the above, please go ahead. Otherwise, I'll poke at it when I have during the week.

> Re. branches: yes, 3.8.2 was a botched up release, which led to a hot-fix release 3.8.3 which was badly merged, and now that affects 4.0.0. Ditching that orphaned branch would have been my choice too but apparently since git diff showed no significant changes between "develop vs. develop+orphan", @mpenkov's choice of merging that branch is actually cleaner – the full history is now in git.

@piskvorky Hang on, the 3.8.3 branch is still an orphan, right? The only trace of that in develop is the CHANGELOG, and we merged that intentionally in https://github.com/RaRe-Technologies/gensim/pull/2831. So yeah, we messed up 3.8.2, but I don't see how 3.8.3 was badly merged.

**Comment by mpenkov** [comment]
@gojomo I had a look at one of the problems, and it's being caused by this:

```
$ git blame gensim/utils.py | grep -C 3 default_rng
e859c11f6 gensim/utils.py     (Michael Penkov     2019-10-25 14:54:24 +0200   49) """An exception that gensim code raises when Cython extensions are unavailable."""
e859c11f6 gensim/utils.py     (Michael Penkov     2019-10-25 14:54:24 +0200   50) 
c0e016956 gensim/utils.py     (Gordon Mohr        2020-07-19 06:15:17 -0700   51) #: A default, shared numpy-Generator-based PRNG for any/all uses that don't require seeding
c0e016956 gensim/utils.py     (Gordon Mohr        2020-07-19 06:15:17 -0700   52) default_prng = np.random.default_rng()
c0e016956 gensim/utils.py     (Gordon Mohr        2020-07-19 06:15:17 -0700   53) 
d9b79e2ff gensim/utils.py     (Radim Řehůřek      2015-04-08 15:18:20 +0200   54) 
255ce2590 gensim/utils.py     (Kumar Akshay       2017-12-26 20:24:31 +0530   55) def get_random_state(seed):
```

At this stage it's probably too late to fix this in gensim (because we'll have to repeat the above release procedure) so should we bump the numpy version that we build the wheels against? If yes, then to what?

**Comment by gojomo** [comment]
What I mean about merges is that if `develop` was deemed reviewed/tested/ready to release, the PR/commit to make a release should be really tiny. But this is appearing to change 550 files, and commit 8624aa2822f885c56996f9a2f84490c9166c84ca seems to have a hundreds-of-lines-long commit message. 

Ideally, nothing that happened wrong in 3.8.2 or 3.8.3 should have any impact now, because `develop` was already the proper true state of what was ready to release. (OTOH, if there *were* some lingering changes on other non-`develop` branches that needed to be in `develop`, they should be brought over in small, reviewable chunks – maybe, cherry-picked? – rather than an opaqueifying big-looking-at-Github (even if the real changes are tiny) merge. 

I guess I just don't understand any necessary process that could create the giant commits/PRs as shown here in the Github web interface. (Maybe it's a Github issue, but even reading the explanation atop this issue, I can't imagine why a couple commits ago, `develop` was straightforward, and the release-steps turned ~5 lines of changes into this giant log.)

WRT to the numpy `default_rng` matter, I think we should just bump our numpy requirement to the one that supplies that. (I thought this had been discussed in a previous issue, but can't recall exactly where.) The fact that this has been working in the main `gensim` repo implies to me that it shouldn't be an issue in release-building, unless the main repo is configured wrong. I previously hadn't taken much note of the separate `gensim-wheels` repo. Could we just make it so the main repo builds the wheels, too? (Fixing anything "in gensim-wheels" rather than in `gensim` seems an anti-pattern to me.) Then releases are definitionally in-sync with whatever's recently had dev attention, and when the main repo builds/tests pass, it's unlikely (or even impossible) for new unforseen release-specific glitches to arise.

**Comment by piskvorky** [comment]
>  I don't see how 3.8.3 was badly merged.

It left `master` vs `develop` in a state that caused our standard release process to unexpectedly blow up during the next release = now.

As long as no "bad changes" (as verified via `git diff`) got in, I don't think it's a big deal. The extra huge commit doesn't really bother me. Although it does make me wonder why such simple merge + conflict resolution wasn't done according to the release process last time, what's the reason for all this, whether there's another gotcha waiting for us somewhere.

**Comment by mpenkov** [comment]
> It left master vs develop in a state that caused our standard release process to unexpectedly blow up during the next release = now.

Looking around, I don't think the merge did that. I'm not sure _what_ did, but a single changelog entry wouldn't have caused this.

I've identified another issue with the wheels on Windows: pip is being stupid and somehow failing to install Cython when installing the wheel:

```
pip install --pre --no-index --force-reinstall --find-links dist/ gensim
Looking in links: dist/
Processing c:\projects\gensim-wheels-2x1bk\gensim\dist\gensim-4.0.0b0-cp36-cp36m-win_amd64.whl
ERROR: Could not find a version that satisfies the requirement Cython==0.29.14 (from gensim) (from versions: none)
ERROR: No matching distribution found for Cython==0.29.14 (from gensim)
```

This is despite it being able to cythonize the files prior to building the wheel.

The wheel itself is getting built and uploaded, but the above error is crashing the build and preventing builds for other Python versions from proceeding.

```
$ aws --profile smart_open s3 ls s3://gensim-wheels/ | grep 4.0.0b0
2020-11-03 16:19:39   23898451 gensim-4.0.0b0-cp36-cp36m-win_amd64.whl
```

**Comment by piskvorky** [comment]
Why would installing a wheel need Cython at all?

**Comment by mpenkov** [comment]
That's a good question. We typically only require cython if the extensions aren't built. In this case, the extensions are getting built, so cython shouldn't be required.

Yet another mystery to unravel.

**Comment by mpenkov** [comment]
This is becoming a bit too much to manage for a single PR (that has been merged anyway), so I've opened separate tickets to deal with the immediate problems:

- https://github.com/RaRe-Technologies/gensim-wheels/issues/7
- https://github.com/RaRe-Technologies/gensim-wheels/issues/8
- https://github.com/RaRe-Technologies/gensim-wheels/issues/9

**Comment by piskvorky** [comment]
> Yet another mystery to unravel.

Yes. Seeing how the other contributions went under the previous stewardship, I should have expected this part would be of similar quality. And focused on more attention there too, prior to the release.

Kudos to @gojomo for insisting on beta.

**Comment by mpenkov** [comment]
I've solved the previous issues, but uncovered two more:

https://github.com/RaRe-Technologies/gensim-wheels/issues/10
https://github.com/RaRe-Technologies/gensim-wheels/issues/11

Currently, all Linux test runs of the wheels are passing (except 3.7). The Windows runs are still failing.

@piskvorky

**Comment by mpenkov** [comment]
Done: https://pypi.org/project/gensim/4.0.0b0/

@piskvorky @gojomo

**Comment by piskvorky** [comment]
@mpenkov thanks a lot!

What are the take aways from releasing 4.0.0beta – anything to improve in our process documentation? Will the next release go smoother?

**Comment by piskvorky** [comment]
@mpenkov I tried on Linux, and `pip install --pre --upgrade gensim` installs 3.8.3.

How do I install 4.0.0beta1?

**Comment by piskvorky** [comment]
Figured it out: the Linux virtualenv had py2.7, so pip installed the latest Gensim where py2.7 worked = 3.8.3.

So, a feature, no problem here :)

**Comment by mpenkov** [comment]
> What are the take aways from releasing 4.0.0beta – anything to improve in our process / documentation? Do we expect the next release go smoother?

Yeah, I can think of two:

1. Build wheels more often (perhaps nightly)
2. Simplify wheel build process (review the multibuild project: is it worth to continue to use it?)

**Comment by gojomo** [comment]
A practice I've liked on previous projects was for each auto-build to actually create the exact same distribution artifacts as a full release - and ideally, also, run the tests from an install of those artifacts. (And keep all of them around, at least for a little while.) Then, there's no separate release build or release repo: an official release is just a tiny labeling change - a version-label-bump of a few lines - then grabbing the exact same artifacts for uploading to official distribution points.

**Pull request merged**
