### PR TITLE
Added SiteGround Hosting to the list of adopters

### PR DESCRIPTION
**Pull request by gogokaradjov**

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Thank you :) @tmylk  can you merge this, please

**Comment by tmylk** [comment]
Is it ok if instead of `Leveraging large amounts of user-generated content` I put `Supervised search with tf-idf and wmd`? Need to state how gensim is used in that column.

**Comment by piskvorky** [comment]
I'd appreciate if the testimonials were a little more concrete in how gensim is being used. What content, what search?

They're meant to serve as "use-cases", so people know how this lib could potentially be used (in rough terms of course, no secret sauce).

**Comment by gogokaradjov** [comment]
Hey guys. I appreciate the feedback. I just commited more to-the-point description of what we use gensim for. Cheers

**Comment by tmylk** [comment]
Sounds good. Thanks!

**Pull request merged**
