### PR TITLE
Test notebooks

### PR DESCRIPTION
**Pull request by amueller**

### CODE REVIEW

**Comment by dsquareindia** [comment]
Just a personal note; I'll get to writing scripts to download the datasets automatically if not present once this is merged. The notebooks should be runnable locally without following links and explicitly downloading datasets.

**Comment by amueller** [comment]
argh many of my python2/python3 fixes were already fixed in develop. Curse you, git flow!

**Comment by amueller** [comment]
I hope this might still be helpful

**Comment by bhargavvader** [comment]
Curious - is this integrated with the travis checks? Or do I check if my notebook has passed by running the `test_notebooks.py` script? 
I'm not sure exactly how to do this, With reference to #921 .

**Comment by amueller** [comment]
I'm actually not sure if the current test call on the CI covers this test.

**Comment by helloLiuLina** [comment]
Exceuse me, I run the code in the 'dtm_example.ipynb', the result every time I run is quite different, Do you have the same problem? Thank you very much!

**Comment by menshikh-iv** [comment]
@helloLiuLina quite different results are OK, try to pass `rng_seed` to `__init__` method.

**Pull request merged**
