### PR TITLE
[WIP] Add support for PySpaRNN (#1224)

### PR DESCRIPTION
**Pull request by markus-beuckelmann**
This wraps Facebook's [PySpaRNN library](http://github.com/facebookresearch/pysparnn) for approximate NN search on sparse data. The interface allows the `PySpaRNNIndexer` object to be used as indexer within gensim, e.g. something like
```
pysparnn_index = PySpaRNNIndexer(model)
model.most_similar([vector], topn = 3, indexer = pysparnn_index)
```

with some arbitrary `vector`.

### CODE REVIEW

**Comment by tmylk** [comment]
Thanks. Please add unit tests for this new feature and a benchmark tutorial

**Comment by tmylk** [comment]
Thanks for the unit tests. Do you think they can be refactored to avoid duplicate code with Annoy tests? The only difference is the indexer

**Comment by markus-beuckelmann** [comment]
True. I refactored the unit tests, which indeed removes quite a bit of redundant code.

**Comment by markus-beuckelmann** [comment]
Two more things:
1. We should probably move the `import` statements for both indexers, because right now I would get an `ImportError` if I ran `from gensim.similarities.index import PySpaRNNIndexer` when `annoy` (!) package is not installed and vice versa. In other words: You can not import either of the two indexers without having both backends installed.
2. How can we make sure that `pysparnn` gets installed in the Travis CI environment?

**Comment by tmylk** [comment]
1) Agree about imports. New file pysparnn_indexer.py is needed in `gensim/similarities` folder just for the new indexer. 

2) To install `pysparnn`  please add it to `.travis.yml` file alongside annoy.

**Comment by markus-beuckelmann** [comment]
Just to give you a heads up, I'm still working on the benchmark notebook. Coming soon!

**Comment by markus-beuckelmann** [comment]
Here is what I get when benchmarking `PySpaRNN` vs. `annoy` on artificial data:
* Benchmarking annoy:
`1 loop, best of 3: 5.08 s per loop`
* Benchmarking PySpaRNN:
`1 loop, best of 3: 817 ms per loop`

So it seems that `PySpaRNN` is indeed significantly faster when the data is sufficiently sparse. The code that produced the above:

```python
import numpy as np
from scipy.sparse import csr_matrix

from annoy import AnnoyIndex
from pysparnn.cluster_index import MultiClusterIndex

# Number of vectors
N = 1000
# Number of features
K = 50000
# Sparsity parameters
f = 0.0005
M = int(np.ceil(f * K))

# Hallucinate a corpus
corpus = [[(a, b) for a, b in zip(np.random.randint(0, K, size = M), np.random.normal(size = M))] for i in range(N)]
# Build the feature matrix
vectors, labels = np.zeros((N, K)), np.arange(0, N, 1)
for i, document in enumerate(corpus):
    for j, x in document:
        vectors[i, j] = x

# Train the Annoy model
a = AnnoyIndex(K)
for i, vector in enumerate(vectors):
    a.add_item(i, vector)
n_trees = 300
a.build(n_trees)

# Train the PySpaRNN model
b = MultiClusterIndex(csr_matrix(vectors), labels)

def test_annoy(model, indices, k = 3):

    for i in indices:
        dense = vectors[i]
        sparse = csr_matrix(dense)
        model.get_nns_by_vector(dense, k)

def test_pysparnn(model, indices, k = 3):

    for i in indices:
        dense = vectors[i]
        sparse = csr_matrix(dense)
        model.search(sparse, k = k, return_distance = False)

# Randomly draw some sample vectors to predict on
indices = np.random.randint(N, size = 100)

print('Benchmarking annoy:')
%timeit test_annoy(a, indices)
print('Benchmarking PySpaRNN:')
%timeit test_pysparnn(b, indices)```

**Comment by markus-beuckelmann** [comment]
I will try it on real–world text data now. Any ideas for sufficiently *sparse* data sets that might be particularly suitable for this?

**Comment by tmylk** [comment]
Thanks. Could you please compare it to a brute-force exact NN with BLAS?

**Comment by tmylk** [comment]
Topic distributions per document are sparse. See an example dataset in #1243

**Comment by markus-beuckelmann** [comment]
* Benchmarking annoy:
` 1 loop, best of 3: 5.01 s per loop`
* Benchmarking PySpaRNN:
`1 loop, best of 3: 759 ms per loop`
* Benchmarking brute–force exact NN:
`1 loop, best of 3: 17.2 s per loop`

**Comment by tmylk** [comment]
Thanks! could you please add the bechmarking ipynb with a tutorial and performance graphs to gensim/docs/notebooks?

Similar to https://github.com/RaRe-Technologies/gensim/blob/ed49ea63fb0e49450e9219423d19b929e0402ec8/docs/notebooks/annoytutorial.ipynb

**Comment by tmylk** [comment]
Ping @markus-beuckelmann

**Comment by markus-beuckelmann** [comment]
> Thanks! Please specify BLAS setup and number of cores.

@tmylk: This is Intel MKL (11.3.3) on an i5 with 2 cores. On full load BLAS uses 4 threads for this. The exact NN mentioned above is the brute–force scikit-learn `NearestNeighbors` [implementation](http://scikit-learn.org/stable/modules/neighbors.html#brute-force).

Busy days, notebook is coming up! I will at least add a work in progress version, tomorrow.

**Comment by menshikh-iv** [comment]
This OL looks almost ready, @markus-beuckelmann can you finish this PR?

**Comment by menshikh-iv** [comment]
I close it, because it is abandoned

**Comment by piskvorky** [comment]
@menshikh-iv It's an awesome feature, and @markus-beuckelmann did a good chunk of work.

I'm -1 on abandoning this. What is actually missing here?

**Comment by markus-beuckelmann** [comment]
@menshikh-iv, @piskvorky: A little late here, sorry for that. Support for PySpaRNN is complete (including unit test) and could be merged. Essentially, the only thing that is missing is the tutorial. I can't finish this right now, but maybe other people are willing to pick it up...

**Pull request closed without merging**
