### PR TITLE
Fix-2253: Remove docker folder since it fails to build  

### LINKED ISSUE #2253: Dockerfile doesn't build
#### Description
dockerfile doesn't build

#### Steps/Code/Corpus to Reproduce
cd docker
docker build .

#### Expected Results
build comples succesfully

#### Actual Results
```
Get:18 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8532 B]
Fetched 15.5 MB in 1s (10.1 MB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.17.1-1ubuntu1.3' for 'wget' was not found
E: Version '2.23-0ubuntu9' for 'locales' was not found
The command '/bin/sh -c apt-get update     && apt-get install -y     ant=1.9.6-1ubuntu1     cmake=3.5.1-1ubuntu3     default-jdk=2:1.8-56ubuntu2     g++=4:5.3.1-1ubuntu1     git=1:2.7.4-0ubuntu1     libboost-all-dev=1.58.0.1ubuntu1     libgsl-dev=2.1+dfsg-2     mercurial=3.7.3-1ubuntu1     python3=3.5.1-3     python3-pip=8.1.1-2ubuntu0.4     python3-setuptools=20.7.0-1     python=2.7.11-1     python-pip=8.1.1-2ubuntu0.4     python-setuptools=20.7.0-1     unzip=6.0-20ubuntu1     wget=1.17.1-1ubuntu1.3     subversion=1.9.3-2ubuntu1.1     locales=2.23-0ubuntu9     libopenblas-dev=0.2.18-1ubuntu1     libboost-program-options-dev=1.58.0.1ubuntu1     zlib1g-dev=1:1.2.8.dfsg-2ubuntu4.1' returned a non-zero code: 100
```

#### Versions
develop branch @ 20181101_2219

### PR DESCRIPTION
**Pull request by FyzHsn**
**Issue**: Dockerfile does not build. See #2253.

**Fix**: This issue is relevant to anyone who is a contributor trying to build a docker image. Since there is no one to maintain the Docker functionality and the image fails to build, the `docker` folder was removed. 

Fixes #2253.

### CODE REVIEW

**Comment by FyzHsn** [comment]
I just looked through all of Gensim for docker related patterns and found an occurrence in the following snippet:

```
Examples
--------
.. sourcecode:: pycon

    >>> from gensim.models.wrappers import Wordrank
    >>>
    >>> path_to_wordrank_binary = '/path/to/wordrank/binary'
    >>> model = Wordrank.train(path_to_wordrank_binary, corpus_file='text8', out_name='wr_model')
    >>>
    >>> print(model["hello"])  # prints vector for given words

Warnings
--------
Note that the wrapper might not work in a docker container for large datasets due to memory limits (caused by MPI).
```

It seems that the context of mentioning `docker` is unrelated to the docker folder in `gensim`. Hence, I'm leaving it there. @piskvorky Is that ok?

**Comment by piskvorky** [comment]
I'd remove that too. It makes no sense to me – using Docker and having enough memory are unrelated topics.

**Comment by FyzHsn** [comment]
@piskvorky I removed the snippet discussing Docker and insufficient memory.

**Comment by piskvorky** [comment]
I saw, thanks. LGTM – let's wait for @mpenkov 's review.

**Pull request merged**
