### PR TITLE
Fix visdom integration (using `viz.line()` instead of `viz.updatetrace()`)

### LINKED ISSUE #2155: "AttributeError: 'Visdom' object has no attribute 'updateTrace'" when running "Training_visualizations.ipynb"
"updateTrace" has been deprecated in the newest version of  Visdom, but it is still being called in Gensim, so failed to run callbacks in "Training_visualizations.ipynb". Hope this issue can be fixed, thanks!
See
https://github.com/facebookresearch/visdom/issues/358

### PR DESCRIPTION
**Pull request by allenyllee**
Visdom had changed it's API according to this post: https://github.com/facebookresearch/visdom/issues/359
Fixes #2155

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Hello @allenyllee, thanks  for the fix: please
- Merge upstream `develop` to your branch (this will fix Travis issue)
- Add a simple test that used a callback (to prevent regression in future).
- Specify `visdom` in https://github.com/RaRe-Technologies/gensim/blob/develop/setup.py#L226 (`visdom >= FIRST_VERSION_THAT_REQUIRED_API_FIX`)
 
after this changes, I'll merge current PR.

**Comment by allenyllee** [comment]
Sorry, this is my first pull request to this project, I don't very understand how to do what you say.
1. Merge what to my branch? the latest commit in the develop branch? and make another pull request?
2. Add to where? which file should I modify to add simple test?

**Comment by menshikh-iv** [comment]
No problem @allenyllee,

(1) Merge `develop` to your branch from current repo, for this you need
- Add remote to your fork: https://help.github.com/articles/configuring-a-remote-for-a-fork/
- Merge `develop` (from original gensim repo) to your branch

(2) Add test in the same way as other tests, see any file in https://github.com/RaRe-Technologies/gensim/tree/develop/gensim/test

**Comment by allenyllee** [comment]
Hi @menshikh-iv , I have done that all you had mentioned, but Travis CI still failed.

**Comment by horpto** [comment]
Hi, @allenyllee 
It is some linter flake8 problems (TravisCI log):

```
gensim/models/callbacks.py:552:110: E231 missing whitespace after ','
                            Y=np.array([value]), X=np.array([epoch]), env=metric.viz_env, win=self.windows[i],update = 'append'
                                                                                                             ^
gensim/models/callbacks.py:552:117: E251 unexpected spaces around keyword / parameter equals
                            Y=np.array([value]), X=np.array([epoch]), env=metric.viz_env, win=self.windows[i],update = 'append'
                                                                                                                    ^
gensim/models/callbacks.py:552:119: E251 unexpected spaces around keyword / parameter equals
                            Y=np.array([value]), X=np.array([epoch]), env=metric.viz_env, win=self.windows[i],update = 'append'
                                                                                                                      ^
gensim/models/callbacks.py:552:121: E501 line too long (127 > 120 characters)
                            Y=np.array([value]), X=np.array([epoch]), env=metric.viz_env, win=self.windows[i],update = 'append'
                                                                                                                        ^
gensim/test/test_lda_callback.py:20:1: F401 'numpy as np' imported but unused
import numpy as np
^
gensim/test/test_lda_callback.py:56:1: E305 expected 2 blank lines after class or function definition, found 1
FLAGS = ARGS()
^
gensim/test/test_lda_callback.py:66:121: E501 line too long (124 > 120 characters)
        self.ch_umass = CoherenceMetric(corpus=self.corpus, coherence="u_mass", logger="visdom", title="Coherence (u_mass)")
                                                                                                                        ^
gensim/test/test_lda_callback.py:138:13: E265 block comment should start with '# '
            #raise AttributeError("test")
            ^
gensim/test/test_lda_callback.py:158:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == '__main__':
^
gensim/test/test_lda_callback.py:160:1: W391 blank line at end of file
^
```

**Comment by allenyllee** [comment]
Hi @menshikh-iv , finally, I have passed all checks!

**Comment by menshikh-iv** [comment]
Thank you @allenyllee :+1:

**Pull request merged**
