### PR TITLE
cElementTree has been deprecated since Python 3.3 and removed in Python 3.9

### LINKED ISSUE #2775: xml.etree.cElementTree was deprecated and removed in Python 3.9 in favor of ElementTree
#### Problem description

xml.etree.cElementTree was deprecated and removed in Python 3.9 in favor of ElementTree

Ref : https://github.com/python/cpython/pull/19108

#### Versions

Python 3.9

I will raise a PR for this issue.

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #2775

### CODE REVIEW

**Comment by piskvorky** [comment]
@mpenkov can you check what's going on with the failing builds? Thanks.

**Comment by tirkarthi** [comment]
Thanks @piskvorky for the quick review

**Comment by piskvorky** [comment]
@tirkarthi can you merge the latest `develop` branch into this PR? That might fix the failing build.

**Comment by piskvorky** [comment]
N/M, I figured I can push to your fork so I merged `develop` myself.

Your PR will become part of the 3.8.3 release this weekend.

**Comment by tirkarthi** [comment]
Thanks again @piskvorky . Take care.

**Pull request merged**
