### PR TITLE
Add per_word_topics parameter to apply call

### PR DESCRIPTION
**Pull request by SND96**
Solving the issue
per_word_topics for a corpus #908

### CODE REVIEW

**Comment by tmylk** [comment]
Thanks for the pr. Please add a line in changelog and a test

**Comment by SND96** [comment]
Can you please advise me on how to proceed to modify the tests.

**Comment by tmylk** [comment]
First please pass *all* the params through the apply call, not just per_word_topics

**Comment by tmylk** [comment]
The tests should be the same as for a single word, just modified to be for a corpus.

**Comment by SND96** [comment]
I passed all the params in the apply call.
`return self._apply(corpus, minimum_probability = self.minimum_probability, minimum_phi_value = self.minimum_phi_value,  per_word_topics = self.per_word_topics)` 

But when I ran this line
`lda.per_word_topics(corpus, per_word_topics = True)`

I got this error
AttributeError: 'LdaModel' object has no attribute 'per_word_topics'

**Comment by tmylk** [comment]
`lda.per_word_topics` calls a non-existing method `per_word_topics`

**Comment by SND96** [comment]
Sorry I ran this,
`lda.get_document_topics(corpus, per_word_topics = True)`

And this was the error I got

> 'LdaModel' object has no attribute 'minimum_phi_value'

**Comment by tmylk** [comment]
which line is it? please report the full error stack

**Comment by SND96** [comment]
I added the attributes `minimum_phi_value` and `per_word_topics` to the attributes of LdaModel class but then this was the error I got

```
In [1]: import logging
   ...: import unittest
   ...: import os
   ...: import os.path
   ...: import tempfile
   ...: import numbers
   ...: 
   ...: import six
   ...: import bumpy
   ...: import scipy.linalg
   ...: 
   ...: from gensim.corpora import mmcorpus, Dictionary
   ...: from gensim.models import ldamodel, ldamulticore
   ...: from gensim import matutils
   ...: 
/Users/sahithdambekodi/Desktop/RaRe/gensim/gensim/utils.py:1014: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
Slow version of gensim.models.word2vec is being used
Slow version of gensim.models.doc2vec is being used

In [2]: texts = [['human', 'interface', 'computer'],
   ...:  ['survey', 'user', 'computer', 'system', 'response', 'time'],
   ...:  ['eps', 'user', 'interface', 'system'],
   ...:  ['system', 'human', 'system', 'eps'],
   ...:  ['user', 'response', 'time'],
   ...:  ['trees'],
   ...:  ['graph', 'trees'],
   ...:  ['graph', 'minors', 'trees'],
   ...:  ['graph', 'minors', 'survey']]
   ...: dictionary = Dictionary(texts)
   ...: corpus = [dictionary.doc2bow(text) for text in texts]
   ...: 

In [3]: from gensim import models

In [4]: lda = models.LdaModel(corpus)

In [5]: lda.get_document_topic(corpus)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-e2a60ca3cb20> in <module>()
----> 1 lda.get_document_topic(corpus)

AttributeError: 'LdaModel' object has no attribute 'get_document_topic'

In [6]: lda.get_document_topics(corpus)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-74e9bbe4f911> in <module>()
----> 1 lda.get_document_topics(corpus)

/Users/sahithdambekodi/Desktop/RaRe/gensim/gensim/models/ldamodel.py in get_document_topics(self, bow, minimum_probability, minimum_phi_value, per_word_topics)
    923         is_corpus, corpus = utils.is_corpus(bow)
    924         if is_corpus:
--> 925             return self._apply(corpus, minimum_probability = self.minimum_probability, minimum_phi_value= self.minimum_phi_value, per_word_topics = self.per_word_topics)
    926 
    927         gamma, phis = self.inference([bow], collect_sstats=True)

TypeError: _apply() got an unexpected keyword argument 'minimum_probability'
```

**Comment by tmylk** [comment]
Almost done in #978

**Pull request closed without merging**
