### PR TITLE
Subpackage refactor. Fix 1584

### PR DESCRIPTION
**Pull request by menshikh-iv**
Fix for #1584.

### CODE REVIEW

**Comment by menshikh-iv** [comment]
I re-create PR according to discussion from #1607 and #1584, please review again @piskvorky @macks22

**Comment by piskvorky** [comment]
Regarding the various `make_wiki_*.py` duplicates: these were originally symlinks. They became duplicates (regular files) only by error.

Removing them will break some functionality, because the script behaves differently based on what filename it was run as.

These parameters are probably better served as proper CLI options, rather than encoded in the filename. Just saying that simply removing the "duplicates" will prevent users from accessing existing functionality.

**Comment by menshikh-iv** [comment]
@piskvorky but how implemented different behavior if all files the same? I don't understand it. Can you show me an example?

**Comment by menshikh-iv** [comment]
Close (because conflict is really big), I'll re-create it with additions when we plan to create major release

**Pull request closed without merging**
