### PR TITLE
Fix dict save as text

### PR DESCRIPTION
**Pull request by vlejd**
Fixing one of #1441 and last problem in #1402.

It changes tests to not use weird characters.

### CODE REVIEW

**Comment by piskvorky** [comment]
-1 on masking errors like this.

**Comment by menshikh-iv** [comment]
I agree with Radim, we should to understand what's a reason of this behaviour and fix it.

**Comment by piskvorky** [comment]
@vlejd What does `56` mean in the title?

**Comment by vlejd** [comment]
I reused the branch referring to issue #56 . I will stop doing it.

**Comment by piskvorky** [comment]
Yes please, a hyperlink in PR description to related issues/PRs is much better and more readable.

**Comment by menshikh-iv** [comment]
Ping @vlejd, what's status of PR?

**Comment by menshikh-iv** [comment]
Resolve in #1469.

**Pull request closed without merging**
