### PR TITLE
replace _mul function with explicit casts

### PR DESCRIPTION
**Pull request by mpenkov**
Follow up from #3136

### CODE REVIEW

**Comment by piskvorky** [comment]
@mpenkov can you remove the (empty) file [16](https://github.com/RaRe-Technologies/gensim/blob/develop/16)? Also added in #3136, probably by mistake.

**Comment by gojomo** [comment]
I personally find this inline, direct approach clearer - so, I prefer it to the `_mul()` function approach. 

But also, I'd suggested previously a `cdef`/`ctypedef` might possibly make it even more compact.  Thinking more about it, it strikes me that best of all could be to explicitly reuse an existing standard numpy type. For example, replacing `<long long>` (which may still have risks of varying meaning across platforms) with `<np.uint64_t>` might best both communicate intent & also ensure uniform behavior across our supported platforms. (If it breaks, it'll break the same everywhere these same `numpy` arrays are being used, which is preferable.)

**Comment by gojomo** [comment]
Would the more-explicit/more-portable `<np.uint64_t>` not have worked?

**Comment by piskvorky** [comment]
I like the explicit width version too.

Writing the comment seems comparable effort to writing the commit – could you help @mpenkov out here? Thanks.

**Comment by gojomo** [comment]
The change would best be done by someone set up to verify it fixes the test case, which I won't be set up to do anytime soon.

**Pull request merged**
