### PR TITLE
[WIP] Distributed word2vec using TensorFlow

### PR DESCRIPTION
**Pull request by saparina**
@menshikh-iv This is a work in progress to add support for distributed word2vec using TensorFlow. 
The existing word2vec_basic from TF is taken and adapted into a distributed execution graph that can be executed on one or multiple nodes.

### CODE REVIEW

**Comment by souravsingh** [comment]
@saparina I believe there is a patch for this at #1222

**Comment by menshikh-iv** [comment]
@saparina I catch exception
```
worker3_1  | Traceback (most recent call last):
worker3_1  |   File "test_distributed_tf.py", line 64, in <module>
worker3_1  |     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
worker3_1  |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
worker3_1  |     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
worker3_1  |   File "test_distributed_tf.py", line 47, in main
worker3_1  |     tfw2v.eval()
worker3_1  |   File "/usr/local/lib/python3.5/dist-packages/gensim-2.3.0-py3.5-linux-x86_64.egg/gensim/models/distributed_word2vec.py", line 354, in eval
worker3_1  |     correct * 100.0 / total))
worker3_1  | ZeroDivisionError: float division by zero
testtfword2vec_worker3_1 exited with code 1
worker2_1  | Task: 1. Average loss at step 44000: 4.6366121959686275. Data index: 11300402. Time: 3309.4427964687347
worker2_1  | Nearest to their: his, its, her, any, the, many, these, my,
worker2_1  | Nearest to who: often, she, he, there, also, never, they, still,
worker2_1  | Nearest to an: akosombo, ineffective, befriends, preceding, obituaries, galway, facetious, specifies,
worker2_1  | Nearest to not: often, generally, able, now, officially, they, usually, courtroom,
worker2_1  | Nearest to which: that, this, what, eichmann, extraterrestrial, bits, usually, lag,
worker2_1  | Nearest to often: usually, commonly, now, there, still, also, generally, who,
worker2_1  | Nearest to is: was, are, has, does, double, makes, although, became,
worker2_1  | Nearest to other: argentine, pen, realistic, balls, bayley, various, fascism, some,
worker2_1  | Nearest to two: three, four, five, six, one, seven, eight, isbn,
worker2_1  | Nearest to of: pet, imposition, fannish, same, wageningen, phodopus, exoskeleton, couplet,
worker2_1  | Nearest to there: they, often, it, still, he, who, she, usually,
worker2_1  | Nearest to one: two, exams, five, four, three, seven, improvised, spice,
worker2_1  | Nearest to during: following, in, under, through, after, before, within, united,
worker2_1  | Nearest to however: but, though, although, when, while, blame, trial, exemplified,
worker2_1  | Nearest to six: seven, four, five, eight, nine, three, two, zero,
worker2_1  | Nearest to and: or, but, broadcasting, unity, though, feline, exclude, bartholomew,
worker2_1  | Time: 3363.257383823395
worker2_1  | Eval analogy file:  questions-words.txt
worker2_1  | Questions:  0
worker2_1  | Skipped:  0
worker2_1  | Traceback (most recent call last):
worker2_1  |   File "test_distributed_tf.py", line 64, in <module>
worker2_1  |     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
worker2_1  |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
worker2_1  |     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
worker2_1  |   File "test_distributed_tf.py", line 47, in main
worker2_1  |     tfw2v.eval()
worker2_1  |   File "/usr/local/lib/python3.5/dist-packages/gensim-2.3.0-py3.5-linux-x86_64.egg/gensim/models/distributed_word2vec.py", line 354, in eval
worker2_1  |     correct * 100.0 / total))
worker2_1  | ZeroDivisionError: float division by zero
testtfword2vec_worker2_1 exited with code 1
```

**Comment by saparina** [comment]
@menshikh-iv it seems like problem with downloading _questions-words.txt_ file, I updated readme. 
Can you run it now?

**Comment by menshikh-iv** [comment]
@saparina  new problem
```
worker2_1  | Traceback (most recent call last):
worker2_1  |   File "test_distributed_tf.py", line 64, in <module>
worker2_1  |     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
worker2_1  |   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
worker2_1  |     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
worker2_1  |   File "test_distributed_tf.py", line 40, in main
worker2_1  |     filename = maybe_download('text8.zip', 31344016)
worker2_1  |   File "test_distributed_tf.py", line 27, in maybe_download
worker2_1  |     'Failed to verify ' + filename + '. Can you get to it with a browser?')
worker2_1  | Exception: Failed to verify text8.zip. Can you get to it with a browser?
```

I run `docker-compose up --build` in folder `tets_tfword2vec`
Current folder status:
```
ivan@P50:~/release/gensim/test_tfword2vec$ ls -laht
total 26M
drwxr-xr-x  2 ivan ivan 4,0K сен 14 15:00 .
-rw-r--r--  1 ivan ivan 590K сен 14 15:00 questions-words.txt
-rw-r--r--  1 ivan ivan  25M сен 14 15:00 text8.zip
drwxr-xr-x 13 ivan ivan 4,0K сен 14 14:58 ..
-rw-r--r--  1 ivan ivan 1016 сен 14 14:58 docker-compose.yml
-rw-r--r--  1 ivan ivan 3,7K сен 14 14:58 Dockerfile
-rw-r--r--  1 ivan ivan  479 сен 14 14:58 README.md
-rw-r--r--  1 ivan ivan 2,4K сен 14 14:58 test_distributed_tf.py
```

**Comment by saparina** [comment]
@menshikh-iv and now it's problem with downloading _text8.zip_. As I see, you didn't download the whole file, because its size must be 31344016, not 26021544. If you can't download it with both `wget` and `curl`, you need to download it from the browser (http://mattmahoney.net/dc/text8.zip), but it's very strange.

**Comment by menshikh-iv** [comment]
Yes, you are correct, the problem was from corrupted corpus, thanks @saparina

**Comment by menshikh-iv** [comment]
I close this PR because the student does not have time now to do this right now, @saparina please reopen PR at any time as you will have time to continue and contact with me.

**Comment by piskvorky** [comment]
Oh, that's a pity :(

**Pull request closed without merging**
