### PR TITLE
Using efficient np.linalg.multi_dot 

### PR DESCRIPTION
**Pull request by maldil**
It is more succinct and effective to refactor code to use `np.linalg.multi_dot` rather than numerous `np.dot` routines.
What do you think about this change that has practical value?

### CODE REVIEW

**Comment by gojomo** [comment]
Can you quantify what the benefit might be, perhaps with a demo showing the improvement?

**Comment by piskvorky** [comment]
Where does Gensim multiply more than 2 matrices (so that multidot has an effect)?

Like @gojomo, a demonstration of the benefits would be nice.

**Comment by gojomo** [comment]
But where would the proposed replacement make any noticeable difference to a Gensim user? 

Is the `print_error()` function that's changed in the PR a major contributor to the runtime of the `svd_error.py` script? How much would a representative usage of that script be sped up by this change?

**Comment by piskvorky** [comment]
Sorry, without a clear demonstration of its benefit, I'm -1 on introducing changes.

If there's a compelling use-case, such as a speed-up when training a new model, or calculating document similarities, please post it here.

**Comment by mpenkov** [comment]
Thank you for your effort @maldil . I see this change has pros and cons.

Pros: more efficient
Cons: more obscure 

Given that efficiency is not a prime concern of the affected code, I think at this stage it's best not to merge this change, because the pros outweigh the cons.

**Pull request closed without merging**
