### PR TITLE
Fix fastText word_vec() for OOV words with use_norm=True

### LINKED ISSUE #2763: FastText OOV word embedding are calculated incorrectly when passing `use_norm=True`
#### Problem description

FastText OOV word embedding are calculated incorrectly when passing `use_norm=True` (particularly, when looking for most similar words).  The library first normalizes n-gram vectors, then averages them. But it should average them first; otherwise, results are inconsistent.

What happens: cosine similarities used for neighbor retrieval are different from similarities calculated directly from word vectors. 

Why it happens:
* usually when calculating vectors for OOV words fasttext calculates average of n-gram vectors
* but if we pass `use_norm=True`, then fasttext calculates average of *L2-normalized* n-gram vectors ([code](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py#L2090)). And it is wrong!
* when we lookup for most similar words, we use just this option, `use_norm=True` ([code](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/keyedvectors.py#L831)), how unfortunate!
* why averaging normalized vectors is wrong: because it was never done when model was trained, and is normally never done when the model is applied, so such vectors are most probably meaningless.
* how to do it right: *first* average n-gram vectors, and *then* normalize them. 

#### Call to action: 
Rewrite `word_vec` method for FastTextKeyedVectors to apply normalization and averaging in the rigth order. 

#### Steps/code/corpus to reproduce
```
word = 'some_oov_word'
pairs = model.most_similar(word)
top_neighbor, top_simil = pairs[0]
print(top_simil)
print(model.cosine_similarities(model[word], model[top_neighbor].reshape(1, -1))[0])
```
these two prints are expected to produce identical numbers (similarity between the oov words and its closest neighbor), but in fact the numbers are different.

This [notebook](https://gist.github.com/avidale/c6b1d13b32a36f19750cd01148560561) reproduces the problem with a particular model for Russian language, but it is relevant for any language. 

#### Versions

The output of 
```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import gensim; print("gensim", gensim.__version__)
from gensim.models import word2vec;print("FAST_VERSION", word2vec.FAST_VERSION)
```
is
```
Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
NumPy 1.17.5
SciPy 1.4.1
gensim 3.8.1
FAST_VERSION 1
```

### PR DESCRIPTION
**Pull request by avidale**
Fixes #2763

### CODE REVIEW

**Comment by gojomo** [comment]
At the moment (through #e7f55c), seems like this only includes a test (good!), but not yet a fix?

**Comment by avidale** [comment]
> At the moment (through [e7f555c](https://github.com/RaRe-Technologies/gensim/commit/e7f555c956839f24c021d5754aca643b1f86c63c)), seems like this only includes a test (good!), but not yet a fix?

That's right. I'll remove the WIP tag after the fix is included.

**Comment by gojomo** [comment]
Fix looks good - though my slightly-different (using `np.linalg.norm`) approach in #2698 will likely supercede. Test is valuable for self-consistency of similarity-paths (one explicitly passing through `use_norm=True`, one not). 

+1 for 'squash & merge'!

**Comment by mpenkov** [comment]
@avidale Congrats on your first PR to gensim! :1st_place_medal:

**Pull request merged**
