### PR TITLE
[MRG] Updated IPython notebook for scikit-learn wrappers

### PR DESCRIPTION
**Pull request by chinmayapancholi13**
Updated scikit-learn IPython notebook to include examples for new models (RP Model and LdaSeq Model) and refactored the code for old models (LDA and LSI models).

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Please create short imports
```python
from gensim.sklearn_integration.sklearn_wrapper_gensim_ldaseqmodel import SklLdaSeqModel
```

To avoid this, you can import all models in `gensim/sklearn_integration/__init__.py` (see [example](https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/__init__.py))

After this, you can replace your imports to 
```python
from gensim.sklearn_integration import SklLdaSeqModel
```

**Comment by tmylk** [comment]
Please add cell output to the ipynb for completeness

**Comment by chinmayapancholi13** [comment]
@menshikh-iv Thanks a lot! :) I have incorporated your suggestion in the `__init__.py` file and in the IPython notebook.

**Comment by menshikh-iv** [comment]
Good work @chinmayapancholi13 :+1:

**Pull request merged**
