### PR TITLE
Fix local import degrading the performance of word2vec model loading …

### PR DESCRIPTION
**Pull request by lopusz**
Fix local import degrading the performance of word2vec model loading (#2671)

### CODE REVIEW

**Comment by lopusz** [comment]
Hi @piskvorky , do you think we can merge this tiny update?

All cheks pass and the update reduces CO2 footprint of word2vec loading... ;)

**Comment by piskvorky** [comment]
In that case let's leave it open! CO2 is vital for life. 8)

Leaving for @mpenkov to review & merge if ready, LGTM.

**Comment by mpenkov** [comment]
I wonder why the original author chose a local import there... and also whether there are other places where we suffer from a similar problem.

Just grepping around, we seem to be importing things outside of module scope (or at least beyond the root level of indentation) quite frequently:

```
$ grep -R "^    " gensim | grep " import " | grep -v ">>>" | cut -d: -f1 | sort | uniq | wc -l
49
```

So, there are 49 modules we may want to review for imports. WDYT @piskvorky ?

**Comment by piskvorky** [comment]
I tracked that import down to the dreadful #1777 by @manneshiva and @janpom . So, how knows.

I expect in many cases these indented imports will be due to `try: except` blocks, or to avoid costly imports or 3rd party (optional) dependencies. But in cases like the one here, I'm +1 on fixing this globally of course.

**Pull request merged**
