### PR TITLE
Added Tensorboard visualization for LDA

### PR DESCRIPTION
**Pull request by parulsethi**
Appended the tutorial to visualize LDA's document-topic distribution

### CODE REVIEW

**Comment by menshikh-iv** [comment]
@parulsethi please round values from vector from viz (they are too long)

**Comment by menshikh-iv** [comment]
1. Display only 5 relevant topics with probabilities
2. Update topic_with_coordinate.png after (1)

**Comment by parulsethi** [comment]
Made requested changes and also updated the embeddings in my [repo](https://github.com/parulsethi/LdaProjector).

**Comment by parulsethi** [comment]
Made requested changes and also updated the embeddings and [train file](https://github.com/parulsethi/LdaProjector/blob/master/train.py) in my [repo](https://github.com/parulsethi/LdaProjector).

**Comment by tmylk** [comment]
Please add what new insight you got from the new clusters in the visualisations.
Can you give names to the clusters?

**Comment by menshikh-iv** [comment]
Good job @parulsethi  :1st_place_medal:

**Pull request merged**
