### PR TITLE
Document that preprocessing.strip_punctuation is limited to ASCII

### PR DESCRIPTION
**Pull request by sciatro**
This PR mitigates issue #2962 by documenting that the function's current behavior is limited to ASCII punctuation.

Issue #2962 includes discussion of approaches to expanding strip_punctuation's behavior to cover unicode punctuation. This PR includes no new functionality / does not implement any of the possibilities considered in the issue. This PR is option 1 of the 3 considered in #2962

### CODE REVIEW

**Review by piskvorky — CHANGES_REQUESTED** [review]
Looks good.

Can you also add a code comment (not docstring – a Python comment at the beginning this function) that links to your ticket with the "3 options"? So it's easier to find, and future contributors know it exists. Thanks!

**Comment by sciatro** [comment]
> Can you also add a code comment

Yes. I've done so.

**Review by piskvorky — APPROVED** [review]

**Review by mpenkov — APPROVED** [review]
Thank you for your contribution!

**Comment by mpenkov** [comment]
Congrats on your first PR to gensim @sciatro 🥇 !

**Comment by piskvorky** [comment]
Reminder to self to update the CHANGELOG entry before release. The current entry makes it sound like `strip_punctuation` accepts only ASCII string, which is not true.

**Pull request merged**
