### PR TITLE
Update bottom -> bottom center for plotly 3.0.0

### LINKED ISSUE #2123: Poincare visualization breaks with plotly 3.0.0
#### Description

poincare_2d_visualization - receives the following error - 
ValueError: 
    Invalid value of type 'builtins.str' received for the 'textposition' property of scatter
        Received value: 'bottom'

#### Steps/Code/Corpus to Reproduce
Example:
```
from gensim.viz.poincare import poincare_2d_visualization
import plotly


vis = poincare_2d_visualization(model, tuples, 'Poincare Plot')
```

#### Versions
Please run the following snippet and paste the output below.
Darwin-17.2.0-x86_64-i386-64bit
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.14.3
SciPy 1.1.0
gensim 3.5.0
FAST_VERSION 1
Plotly 3.0.0

### PR DESCRIPTION
**Pull request by brettbj**
Fixes #2123

### CODE REVIEW

**Comment by piskvorky** [comment]
I don't think this code path is autmatically tested through our unit tests.

How did you test it @brettbj ? Does it work in both old and new versions of plotly?

**Comment by brettbj** [comment]
@piskvorky Sorry I had patched only for new versions. I will add a check for version when I get a chance.

**Comment by menshikh-iv** [comment]
I checked,  `textposition="bottom center"` works fine for 2+ and 3+ versions plotly versions, but for 3+ need also fix 2 parameters: `mode="line", hoverinfo=False`, @brettbj I hope that you a have chance to do it now.

**Comment by menshikh-iv** [comment]
ping @brettbj, are you planning to finish this PR?

**Comment by menshikh-iv** [comment]
Close, because PR are abandoned.

**Comment by piskvorky** [comment]
@brettbj can you finish this up? It'd be great to support the latest plotlly. Cheers.

**Pull request closed without merging**
