### PR TITLE
Inferring topics over a new author in the author-topic model

### PR DESCRIPTION
**Pull request by olavurmortensen**
At the moment, it is not possible to get a topic representation of a new author in the author-topic model in Gensim. Users are interested in this capability, for example in [this question](https://groups.google.com/forum/#!topic/gensim/HYcLC82ZK78) on Gensim's Google group. Typically, users want this functionality to be able to predict the author of the input documents, which can be achieved using a similarity query.

Because of the apparent interest, I'm going to look into this. Since it has been some time since I worked on the author-topic model, I first must assess what needs to be done.

### CODE REVIEW

**Comment by menshikh-iv** [comment]
@olavurmortensen are you planning to continue PR, I'm correct?

**Comment by olavurmortensen** [comment]
@menshikh-iv Yes. If it is relatively straight forward to implement, I will do it. If it requires a lot of work, I won't have time to do it.

**Comment by menshikh-iv** [comment]
@olavurmortensen thanks for the clarification, please keep me informed.

**Comment by menshikh-iv** [comment]
Ping @olavurmortensen, do you have the time to continue PR?

**Comment by Stamenov** [comment]
I think I might be working on a PR for this problem, already discussed it with Olavur. Although maybe via my own separate PR.

**Comment by menshikh-iv** [comment]
Thanks for info @Stamenov, ok, I close this PR and wait for PR from you @Stamenov.

**Pull request closed without merging**
