### PR TITLE
most_similar_cosmul bug fix

### PR DESCRIPTION
**Pull request by dkim010**
remove `unhashable type: 'numpy.ndarray'` error

Signed-off-by: Dongwon Kim <dongwon.kim@navercorp.com>

### CODE REVIEW

**Comment by tmylk** [comment]
Thank you for the quick fix!

`model.most_similar_cosmul('graph', topn=10)` works but `model.most_similar_cosmul(positive=[graph_vector], topn=11)` still produces results `TypeError: unhashable type: 'numpy.ndarray'`.

Please add this unit test to `test_word2vec.py`
```
def test_cosmul():
        model = word2vec.Word2Vec(sentences, size=2, min_count=1, hs=1, negative=0)
        sims = model.most_similar_cosmul('graph', topn=10)
        # self.assertTrue(sims[0][0] == 'trees', sims)  # most similar

        # test querying for "most similar" by vector
        graph_vector = model.wv.syn0norm[model.wv.vocab['graph'].index]
        sims2 = model.most_similar_cosmul(positive=[graph_vector], topn=11)
        sims2 = [(w, sim) for w, sim in sims2 if w != 'graph']  # ignore 'graph' itself
        self.assertEqual(sims, sims2)
```

**Comment by dkim010** [comment]
Thank you for the quick reply!

I think that `most_similar_cosmul()` method allows only the string (or a string list) as the positive/negative parameters.
The method is related to the `most_similar()` method and both methods cannot pass the vectors of the words.
Is my idea wrong?

**Comment by tmylk** [comment]
`most_similar` works with vectors and `most_similar_cosmul` is expected to work too https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/test/test_word2vec.py#L360

**Comment by dkim010** [comment]
Okay, I'll fix it.

**Comment by dkim010** [comment]
I fixed it. `most_similar_cosmul` works with vectors!
I refered `most_similar`.

**Comment by tmylk** [comment]
Thanks for the quick fix!

**Pull request merged**
