### PR TITLE
Created tutorial notebook on news classification with gensim

### PR DESCRIPTION
**Pull request by dsquareindia**
@tmylk I've added the tutorial notebook on news classification with gensim. Could you please review?

### CODE REVIEW

**Comment by amueller** [comment]
"coughs out" seems needlessly obscure

**Comment by amueller** [comment]
This seems like it was not written in the context of the gensim docs. I'd rewrite it a bit to change things like where to find gensim, or the version requirements.

**Comment by amueller** [comment]
Can you make it Python3 compatible? Is CI not running the tutorial notebooks?

**Comment by dsquareindia** [comment]
@amueller I've addressed the comments. Does this look better?

**Comment by dsquareindia** [comment]
No CI doesn't run on notebooks :/

**Pull request merged**
