### PR TITLE
Remove plotly's dendrogram code in notebooks

### PR DESCRIPTION
**Pull request by parulsethi**
Removed the modified dendrogram code from visualization notebooks, as https://github.com/plotly/plotly.py/pull/807 has been merged.

### CODE REVIEW

**Comment by menshikh-iv** [comment]
@parulsethi I don't see new plotly release, it's not released yet?

**Comment by parulsethi** [comment]
Yeah, my addition is in their `master` branch for now. We can either add a note in the notebook to clone and install plotly directly from github to use the visualization or else wait for the next release.

**Comment by menshikh-iv** [comment]
@parulsethi 
Fix concrete `plotly` version in your notebook (for example, cells with `pip install plotly==needed_version`) + description why you need this version. You should do it after plotly official release and I'll merge this.

**Comment by menshikh-iv** [comment]
I pinned needed plotly version & re-run notebook, thanks @parulsethi :star2:

**Pull request merged**
