### PR TITLE
DTM detailed tests.

### PR DESCRIPTION
**Pull request by bhargavvader**
This PR contains the detailed tests and test files for DTM as well as an example notebook detailing how to use it. 

The tests in this pr should not be merged in but are a useful resource to troubleshoot DTM problems.

A much more concise set of tests has been merged in for DTM.

### CODE REVIEW

**Comment by tmylk** [comment]
Thanks. This should stay as a good test-suite which is needed to investigate DTM Python but shouldn't be part of the main package as it is too bulky.

**Comment by tmylk** [comment]
@bhargavvader There are errors building on windows

```
======================================================================
ERROR: testTopicWord (gensim.test.test_ldaseqmodel.TestLdaSeq)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gensim\test\test_ldaseqmodel.py", line 31, in setUp
    self.ldaseq = ldaseqmodel.LdaSeqModel(corpus = corpus , id2word= dictionary, num_topics=2, time_slice=[10, 10, 11], initialize='own', sstats=sstats)
  File "C:\Python27\lib\site-packages\gensim\models\ldaseqmodel.py", line 161, in __init__
    self.fit_lda_seq(self.corpus, lda_inference_max_iter, em_min_iter, em_max_iter)
  File "C:\Python27\lib\site-packages\gensim\models\ldaseqmodel.py", line 209, in fit_lda_seq
    logger.info(" EM iter ", iter_)
  File "C:\Python27\lib\logging\__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Python27\lib\logging\__init__.py", line 1286, in _log
    self.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "C:\Python27\lib\logging\__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 759, in handle
    self.emit(record)
  File "C:\Python27\lib\site-packages\nose\plugins\logcapture.py", line 82, in emit
    self.buffer.append(self.format(record))
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by bhargavvader** [comment]
Hmm, this is a problem with `logger.info`. Any idea if this fails in other places too on Windows?

**Comment by piskvorky** [comment]
It looks like the `info` format string is missing the argument placeholder (just like the error says)?

**Comment by tmylk** [comment]
Closing. It should be preserved in the repo but not merged in.

**Pull request closed without merging**
