### PR TITLE
Automatic validation of your citation metadata

### PR DESCRIPTION
**Pull request by abelsiqueira**
Hello!

We noticed that your repository is using the Citation File Format to store citation metadata in `CITATION.cff`. This Pull Request automates validation of that file using the [cffconvert GitHub Action](https://github.com/marketplace/actions/cffconvert). That way, it's a little bit easier to be robust against future changes to the `CITATION.cff` file.

BTW it's perfectly fine if you don't feel like accepting this Pull Request for whatever reason -- we just thought it might be helpful is all.

We found your repository using a partially automated workflow; if you have any questions about that, feel free to create an issue over at https://github.com/cffbots/filtering/issues/

On behalf of the cffbots team,
@abelsiqueira / @fdiblen / @jspaaks

### CODE REVIEW

**Comment by piskvorky** [comment]
@mpenkov WDYT? Seems an overkill to me (the Gensim license hasn't changed in 10 years, and likely never will).

**Comment by abelsiqueira** [comment]
Hi @piskvorky, just a clarification. This action verifies the `CITATION.cff` file, not the license.

**Comment by piskvorky** [comment]
Sure. But same thing – the citation hasn't changed in 10 years, and likely never will. `CITATION.cff` is just the latest incarnation of a "quotation format", we've gone through a few already :)

**Comment by abelsiqueira** [comment]
Absolutely, I just wanted to make sure that the PR intent was clear. And I agree, it can be overkill for some projects. Some people like a fully static `CITATION.cff`, but some people like to keep tabs and update things like `authors`, `version`, `date-released`, `references` and `preferred-citation`. But this is a personal choice, and I am not promoting one way or the other, just advertising the validator in case this project is leaning to the latter ;). But again, feel free to close this PR, no hard feelings :+1:

**Comment by piskvorky** [comment]
We decided we don't need this since the CFF file never changes in Gensim. Thanks for your suggestion!

**Pull request closed without merging**
