### PR TITLE
gensim wrappers single vs double quote issue in windows revsolved

### LINKED ISSUE #671: LDAmallet shows the same words repeated for all the topics
I run the LDAmallet to generate topics. The results show problem in the implementation.

`# READ DOCUMENTS

```
file_paths = [os.path.join(dir_data, fname) for fname in os.listdir(dir_data) if fname.endswith(".txt") ]
documents = [codecs.open(file_path, 'r', encoding="utf8", errors='ignore').read() for file_path in file_paths ]

# USING NLTK TOKENIZER TO SEPERATE WORDS

tokenizer = RegexpTokenizer(r'\w+')

texts = []
for each in documents:
    tokens = tokenizer.tokenize(each)
    texts.append(tokens)

dictionary = corpora.Dictionary(texts)

corpus = [dictionary.doc2bow(text) for text in texts]

num_topics=numberOfTopics
mallet_path = "C:/mallet-2.0.7/bin/mallet"
ldamodel = gensim.models.wrappers.LdaMallet(mallet_path, corpus, num_topics, dictionary, 4, dir_data, 0 ,1000)

result = (ldamodel.show_topics(num_topics, num_words,formatted=False))
for each in result:
    print each
```

`
However, the output shows the same words repeated for all the topics and a warning for division by 0 when tries to normalize the weights. The output looks like this

`Warning (from warnings module):
  File "C:\Python27\lib\site-packages\gensim\models\wrappers\ldamallet.py", line 239
    topic = topic / topic.sum()  # normalize to probability dist
RuntimeWarning: invalid value encountered in divide
... LDA Model Trained ....
[(nan, u'b1e'), (nan, u'mokak'), (nan, u'viyac'), (nan, u'stipu'), (nan, u'forchange'), (nan, u'dugayiynggu'), (nan, u'hayne'), (nan, u'enrichment'), (nan, u'boseley'), (nan, u'releasesfresh')]
[(nan, u'b1e'), (nan, u'mokak'), (nan, u'viyac'), (nan, u'stipu'), (nan, u'forchange'), (nan, u'dugayiynggu'), (nan, u'hayne'), (nan, u'enrichment'), (nan, u'boseley'), (nan, u'releasesfresh')]
[(nan, u'b1e'), (nan, u'mokak'), (nan, u'viyac'), (nan, u'stipu'), (nan, u'forchange'), (nan, u'dugayiynggu'), (nan, u'hayne'), (nan, u'enrichment'), (nan, u'boseley'), (nan, u'releasesfresh')]
......
`

It is also worth mentioning that the state.mallet.gz output file is almost empty it contains only:

`#doc source pos typeindex type topic
# alpha : 5.0 5.0 5.0 5.0 5.0 5.0 5.0 5.0 5.0 5.0
# beta : 0.01

`

While the corpus.txt looks good 

`0 0 rest participate apply education attend motivate note application charge interest must local interstate natsiec complete form regional free train half day day day volunteer volunteer volunteer volunteer volunteer volunteer volunteer volunteer look receive
1 0 education education education education train train train train train deputy relate national executive executive number general vocational robinson robinson robinson robinson service employment employment numerou responsible unite research field role role department department department department department include chri chri kingdom prime commissioner commissioner manage centre government government cabinet director director five minister child hold hold hold appoint asqa chief chief chief period officer position senior senior
   .........`

but I am not sure about doctopics.txt output file 

`#doc name topic proportion ...
0   0   5   0.11538461538461539 3   0.11538461538461539 9   0.09615384615384616 8   0.09615384615384616 7   0.09615384615384616 6   0.09615384615384616 4   0.09615384615384616 2   0.09615384615384616 1   0.09615384615384616 0   0.09615384615384616 
`

I thought the document name should be the complete name not ID? Any idea where I went wrong?

Thanks

### PR DESCRIPTION
**Pull request by prakhar2b**
Fix #671 According to discussion, a review of all process calls in gensim wrappers was needed, to make sure the quotes are correct for Windows too.

### CODE REVIEW

**Comment by tmylk** [comment]
Are there any other process calls with thiis issue? would be good to fix them all in one PR

**Comment by prakhar2b** [comment]
Note: As suggested in this [comment](https://github.com/RaRe-Technologies/gensim/issues/671#issuecomment-217595212) in #671 , I reviewed all process calls in gensim [wrappers](https://github.com/RaRe-Technologies/gensim/tree/develop/gensim/models/wrappers), to make sure the quotes are correct for Windows too. 

On a side note, the issue was already solved by making changes in the function `convert_input` according to the code used by the user who opened the issue, but the same changes applied to other functions and in other wrappers too.

More about ```single vs double quote in windows``` [here](http://stackoverflow.com/questions/24173825/what-does-single-quote-do-in-windows-batch-files)

**Comment by tmylk** [comment]
Thanks for the pr

**Comment by piskvorky** [comment]
I think you misunderstood the issue. Windows OS needs double quotes in the strings we pass to it, but that has nothing to do with the changes in this PR.

The changes in this PR are a no-op -- they just reformat the Python strings, not their content.

@tmylk did you review there are no other single quotes *inside* strings being passed to Windows?

**Comment by prakhar2b** [comment]
@piskvorky ok, I really misunderstood it. Now, I understand the issue. 

I grepped through all the files, and I found one instance of such pattern- this [line](https://github.com/RaRe-Technologies/gensim/blob/develop/ez_setup.py#L44)
>msg = "Command '%s' return non-zero exit status %d" % (cmd, res)

I can assure there are no other such instances. Thanks.

**Pull request merged**
