### PR TITLE
[MRG] New docs theme

### LINKED ISSUE #2927: RFC: New website design
I've hired a designer to redesign the Gensim website, give it a more modern & unified look for our 4.0 release.

I asked them to keep the same content + structure = static "plain HTML" pages for the "outside" website, plus auto-generated docs for the "inside" API ref. Just looking better than the current https://radimrehurek.com/gensim/.

The designer came up with the following options. They are generic templates, to be customized and filled with content, so it's only about the general look&feel at this point.

### "Outside" pages

* http://be.beantownthemes.com/html/index-erp2.html
* http://be.beantownthemes.com/html/content/electronics/contact.html
* http://be.beantownthemes.com/html/index-landing2.html
* http://be.beantownthemes.com/html/index-app4.html
* http://be.beantownthemes.com/html/index-mechanic4.html
* http://be.beantownthemes.com/html/index-pay2.html
* http://preview.themeforest.net/item/saasbox-multipurpose-html-template-for-saas/full_screen_preview/25607146
* https://preview.themeforest.net/item/jumpstart-app-and-software-template/full_screen_preview/24207799
* http://preview.themeforest.net/item/landrick-responsive-saas-and-software-template/full_screen_preview/24438577

### "Inner" API reference pages

* https://sphinx-rtd-theme.readthedocs.io/en/stable/
* http://docs.guzzlephp.org/en/stable/
* https://bashtage.github.io/sphinx-material/

@gojomo @mpenkov any preference? Your input and comments are welcome. Otherwise I'll go ahead and pick something, not critical. Cheers.

### PR DESCRIPTION
**Pull request by dvorakvaclav**
Fixes #2927.

For info, I don't know if it's only for me, but in order to generate the docs I had to remove one letter from line 1261 in `gensim/utils.py`: `Yield chunks as `np.ndarray`s instead of lists?`. Otherwise the doc generation process ended with the error `gensim/utils.py:docstring of gensim.utils.chunkize:9:Inline interpreted text or phrase reference start-string without end-string`. This change is not included in this PR – just the files from `docs/src`.

### CODE REVIEW

**Comment by gojomo** [comment]
With no opinion on any of the actual core content here, this seems like a lump of files that perhaps *shouldn't* be inside the open-source library source-control. The project previously had about ~850 files; this PR changes 2111 files. It includes 1300+ SVG files, 300+ JPGs, and 50+ PHP (?!?) files. But I'm not sure there's yet any actual docs (rather than just styling) in this grouping. Perhaps this belongs in some separate "website" git project?

**Comment by piskvorky** [comment]
I'm sure most of the files are not needed. @dvorakvaclav can you trim this PR down please? Let's review & commit & maintain only what we actually need.

**Comment by dvorakvaclav** [comment]
We deleted over 2000 unnecessary files imported from original html theme including old sphinx gensim theme. Now there should be only files, that are actually used.

**Comment by piskvorky** [comment]
My review from Trello (sorry guys, Czech only):

1. Social ikony dole jsou zabite: facebook ikona vede na github, github ikona chybi, ta treti ikona nevim co je. Celkove je tato sekce nepekna, ikony jsou umistene divne, bez logiky stranky. Prosim "socializovat" nejak lepe.
2. Favicon lepe pozitivni verzi (bez tmaveho pozadi)?
3. U sekce "Scalable statistical semantics
Analyze plain-text documents for semantic structure
Retrieve semantically similar documents" jako navstevnik nevim, na co se divam. Sloupce nijak oddelene, hesla se k nicemu nevztahuji, ani u nich neni zadna ikona nebo obrazek.
Pohledem na puvodni verzi toto byl "checklist" hlavnich benefitu Gensimu. Prosim body presunout nad sample kod (nebo vedle?), namisto tlacitka "Explore all features", ktere nepotrebujem, a nejak je lepe vizualizovat.
4. Kliknuti na odkazy ke stazeni (napr. Download Python source code: run_core_concepts.py nebo Download Jupyter notebook: run_core_concepts.ipynb v docs/auto_examples/core/run_core_concepts.html, a nejspis i jinde) by melo soubor stahnout. Ne otevrit v prohlizeci jako text.
5. Chrome mi ukazuje chybu pri stahovani jednoho souboru, transport.png: Access to image from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
6. Poskakovani stranky pri (automatickem) posunovani v sekci Who is using Gensim? je velice neprijemne.
Jak budeme v budoucnu menit (pregenerovat) ten syntax-highlighted sample kod nahore? Jaky je zde postup.
7. Stahovat 3MB na jednoduche staticke strance je docela dost. Napada vas, jak page load optimalizovat / urychlit? (krome CDN, kde pouzivame CloudFlare)


Otherwise build generation works, tested locally 👍  I have to remember to re-apply 0b12d9dbfab21bb32d5be401a37f4a0380bb62ba (new commit in `develop` missing from this PR).

**Comment by piskvorky** [comment]
@dvorakvaclav I committed fixes & changes to the page copy into https://github.com/RaRe-Technologies/gensim/tree/new_docs_theme. **Please merge that into this PR first, before any further changes, to avoid git conflicts**.

**Comment by piskvorky** [comment]
I rebased & force-pushed, to remove the extra 2k files from our repo git history.

**Comment by piskvorky** [comment]
@gojomo @mpenkov final version here: https://radimrehurek.com/gensim_redesign/

Have a look and let me know – otherwise I'll merge tomorrow, the redesign is complete!

**Pull request merged**
