### PR TITLE
Fix `keep_n` behavior for `Dictionary.filter_extremes`

### LINKED ISSUE #2230: The keep_tokens parameter for Dictionary.filter_extremes does not work properly
The documentation of the `filter_extremes` method of `gensim.corpora.Dictionary` states for the `keep_tokens` parameter: "Iterable of tokens that **must** stay in dictionary after filtering." 

However, if filtering by the `keep_n` parameter is applied, those tokens can still get removed. 

This is due to the code around line 358 in gensim/corpora/dictionary.py where the ids are first sorted by document frequency in reverse order and then the first `keep_n` of those indices are taken. However, if the tokens listed in `keep_tokens` are rare and not within the `keep_n` most frequent ones, they get removed by this. 

The expected behaviour would be that the tokens listed in `keep_tokens` never get removed.

### PR DESCRIPTION
**Pull request by johann-petrak**
If keep_tokens are specified, this fixes the problem by using a lambda for
sorting which returns a fake document frequence equal to the number of documents
for all tokens in the keep list.

Fix #2230

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Thanks for PR @johann-petrak, can you
1. Add test for this case (to avoid regression in future)
2. Merge latest `develop` to your branch (outdated base branch is an reason of failed CircleCI)

For last you need
- Configure remote for your fork (current gensim repo) https://help.github.com/articles/configuring-a-remote-for-a-fork/
- Merge `upstream/develop` to your branch: https://help.github.com/articles/syncing-a-fork/

**Comment by johann-petrak** [comment]
Thanks! Sorry, still not too familiar with pull requests in general and gensim in particular. 
So - the development branch is the one which should be used to get the latest development head and for testing and fixing issues?

**Comment by johann-petrak** [comment]
I *think* this should be ready to get merged, please let me know if anything should be still missing.

**Comment by johann-petrak** [comment]
Sorry to bump this, but I did think I did everything necessary, is there still anything missing from my side?

**Comment by piskvorky** [comment]
@johann-petrak thanks a lot! We'll get to open source in a few weeks (swamped now). Is merging this PR urgent for you?

**Comment by johann-petrak** [comment]
Not really urgent just wondered if there might still something missing.

**Comment by menshikh-iv** [comment]
Sorry for waiting, thanks for PR @johann-petrak :+1:

**Pull request merged**
