### PR TITLE
Docker instructions in README.rst

### PR DESCRIPTION
**Pull request by zmarty**
Add instructions to quickly start a Docker image that has gensim and all its dependencies already installed.

### CODE REVIEW

**Comment by zmarty** [comment]
The CI failure is unrelated to my change, I checked.

**Comment by piskvorky** [comment]
@tmylk please comment out @gojomo 's tests that keep failing. This is a problem on many PRs.

**Comment by gojomo** [comment]
While a few of those test failures are a near-miss on one of the Word2Vec tests (about which I'll comment in #531), many more of the (AppVeyor) failures appear to be a different test:

    FAIL: testTransform (gensim.test.test_ldamodel.TestLdaMulticore)

`TestLdaMulticore.testTransform` fails 0 out of the 45 TravisCI runs, but **22 out of 36** AppVeyor runs. There's definitely a platform-specific difference there, and that's the main blocker for the AppVeyor builds.

Meanwhile, `TestWord2VecModel.test_cbow_hs` appears to trigger a failure 2 out of the 45 (9 runs * 5 configs) TravisCI runs, and 3 out of the 36 AppVeyor runs. There *might* be a platform-related difference there. (I wouldn't normally think so with such a small difference, but given the big TestLDAMulticore difference, I have to wonder.)

Additionally, there were 6 tests on AppVeyor that hung at `Test word2vec parallel training. ... ` (for example: https://ci.appveyor.com/project/piskvorky/gensim/build/1.0.31/job/0vfdwx53lugeocvm). That *might* be a symptom of the race-condition issue described in #571.

**Comment by piskvorky** [comment]
I'd vote for sorting the tests out before our next release, one way or another. This is too confusing to contributors. (sorry to @zmarty for off topic)

On topic: docker is a great idea, there have been several requests on the mailing list, even offers of help. 

In contrast to this PR, I'd go with linking/building our own images (not rely on 3rd party). And also making the instructions more explicit and verbose -- I am not a docker expert, and its slew of options (`--rm`, `-it`, "scripts" under `/usr/local`, python3) make me a little uncomfortable.

How do other Python projects handle this? @tmylk? Make we can inspire ourselves there :)

**Comment by piskvorky** [comment]
Related: issue #497 and [this mailing list discussion](https://groups.google.com/forum/#!topic/gensim/DYad1y74ZQA).

**Comment by tmylk** [comment]
Best deployment options are provided by [spark-notebook](https://github.com/andypetrella/spark-notebook) project.

The easiest one is:

```
docker pull andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.4.0
docker run -p 9000:9000 andypetrella/spark-notebook:0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.4.0
```

We should host gensim docker container in the registry instead of asking users to build it. @zmarty Have you used Docker Registry before?

**Comment by zmarty** [comment]
Hello!

1) Docker containers are supposed to be lightweight. I created one with only gensim.
2) This is already in the registry and it is pre-compiled. In fact, Docker auto-builds it. I am not asking users to build anything. The extra mkdir command is to make sure that they do not lose their file. The example you gave requires running two commands. The example I gave also requires running two commands.
3) You can take a look at the Dockerfile here: https://hub.docker.com/r/zmarty/python3-gensim-doc2vec/~/dockerfile/

Thanks,
Ovi

**Comment by zmarty** [comment]
Let's continue the discussion in the other linked item.

**Comment by tmylk** [comment]
HI @zmarty, Thinking about it some more. Maybe we should add ipython notebook and open it in the ipynb  tutorials folder of gensim on start up? 
That way it will be more friendly to beginners.

**Comment by zmarty** [comment]
Sorry if I do not understand what you mean. Do you mean that when the container starts up, it should show a tutorial for gensim in an ipython notebook? If that is what you mean, we can probably do that as long as we can display the notebook in text mode, as this will all run in the console. I only saw these notebooks in the browser so far, do they also open in text mode?

**Comment by tmylk** [comment]
I am just copying the spark notebook approach here. See their docker readme
on github.

The container starts with the notebook port forwarded to localhost and
shows a message inviting user to open localhost:8888 on the host machine.

**Comment by zmarty** [comment]
Update: I have modified the Dockerfile to conform to the best practices guide: https://docs.docker.com/engine/articles/dockerfile_best-practices/ as suggested here: https://github.com/docker-library/official-images

I will next work on exposing the notebook as you suggested.

**Comment by menshikh-iv** [comment]
I close this PR because we will soon have our docker-image ready from [PR1368](https://github.com/RaRe-Technologies/gensim/pull/1368)

**Pull request closed without merging**
