### PR TITLE
Fix formula in Mallet documentation

### PR DESCRIPTION
**Pull request by Laubeee**
its not displayed right in https://radimrehurek.com/gensim/models/wrappers/ldamallet.html

### CODE REVIEW

**Comment by menshikh-iv** [comment]
@Laubeee hello, thanks for PR, please check documentation build log and fix issue https://circleci.com/gh/RaRe-Technologies/gensim/1502?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, after I'll merge your PR

**Comment by Laubeee** [comment]
hey, circle CI is fixed, dunno why travis is now failing, my change has nothing to do with the FastTextModel..

**Comment by menshikh-iv** [comment]
@Laubeee I re-run Travis (this is not-deterministic tests), don't worry about it.
Though issue with rendering still here (but new)
image

looks like you miss `\` before `_`, can you fix it please.

**Comment by menshikh-iv** [comment]
Thanks for PR @Laubeee :+1:

**Pull request merged**
