### PR TITLE
Remove wrappers

### PR DESCRIPTION
**Pull request by mpenkov**

### CODE REVIEW

**Comment by piskvorky** [comment]
Thanks! What's the relationship between this PR and #2972?

**Comment by mpenkov** [comment]
Ah, it's redundant. I think the only thing useful here is the Cython version bump.

**Comment by mpenkov** [comment]
Thanks for reminding me about #2972, I'll take it from there.

**Comment by piskvorky** [comment]
This PR also removed the sklearn wrappers (which is desirable), while #2972 didn't.

**Comment by mpenkov** [comment]
Yeah, that part was trivial. I did this while in transit, which is why I neglected to check for #2972.

**Pull request closed without merging**
