### PR TITLE
Fix unit test initialisation issue for test_wikicorpus.py, fix#956

### LINKED ISSUE #956: Fix unit test initialisation issue for test_wikicorpus.py
In reference to the issue mentioned [here](https://github.com/RaRe-Technologies/gensim/pull/929#issuecomment-252508025) in PR [#929](https://github.com/RaRe-Technologies/gensim/pull/929) and this [Travis error.](https://travis-ci.org/RaRe-Technologies/gensim/jobs/167991024#L1477) 

`No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.`

The test file `test_wikicorpus.py` doesn't throw any test errored/pass message.

### PR DESCRIPTION
**Pull request by markroxor**
Initialising unittest for TestWikiCorpus ,fix #956

### CODE REVIEW

**Comment by markroxor** [comment]
Both(python 2.7.9 and python 3.4.2) builds pass on my VM.

**Comment by tmylk** [comment]
2.7 test still hangs in the same way. Are you sure that this is the solution?

**Comment by markroxor** [comment]
It works fine on my VM and [Travis](https://travis-ci.org/markroxor/gensim/builds/168503292). I can't imitate the error.

**Comment by tmylk** [comment]
did it work fine before this change too?

**Comment by markroxor** [comment]
It worked fine but did not throw any message (whether the test was `ok` or not) as in

**Comment by tmylk** [comment]
how did you run it? so what is the reason for this change?

**Comment by markroxor** [comment]
I followed .travis.yml on my VM. 
All the other test_xx.py files include 
`if __name__ == '__main__':`
`     logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.DEBUG)`
`     unittest.main()`
so that the testxxx methods are invoked. Also according to the [documentation](https://docs.python.org/2/library/unittest.html#basic-example).

**Comment by tmylk** [comment]
Sure, thanks for the PR

**Pull request merged**
