### PR TITLE
Removed FuzzyTM dependency from setup.py

### LINKED ISSUE #3423: Unnecessary dependency on FuzzyTM pulls in many libraries
#### Problem description

I'm trying to upgrade to the new Gensim 4.3.0 release. My colleague @juhoinkinen noticed in https://github.com/NatLibFi/Annif/pull/660 that Gensim 4.3.0 pulls in more dependencies than the previous release 4.2.0, including pandas. I suspect that at least the FuzzyTM dependency (which in turn pulls in pandas) is actually unused and thus unnecessary.

#### Steps/code/corpus to reproduce

Installing Gensim 4.2.0 into an empty venv (only four packages installed):

```
$ pip install gensim==4.2.0
Collecting gensim==4.2.0
  Downloading gensim-4.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 2.0 MB/s eta 0:00:00
Collecting scipy>=0.18.1
  Downloading scipy-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 3.3 MB/s eta 0:00:00
Collecting numpy>=1.17.0
  Downloading numpy-1.24.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 10.6 MB/s eta 0:00:00
Collecting smart-open>=1.8.1
  Downloading smart_open-6.3.0-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 KB 9.7 MB/s eta 0:00:00
Installing collected packages: smart-open, numpy, scipy, gensim
Successfully installed gensim-4.2.0 numpy-1.24.1 scipy-1.10.0 smart-open-6.3.0
```

Installing Gensim 4.3.0 into an empty venv (18 packages installed):

```
$ pip install gensim==4.3.0
Collecting gensim==4.3.0
  Downloading gensim-4.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 6.9 MB/s eta 0:00:00

[...skipping downloads...]

Installing collected packages: pytz, urllib3, smart-open, six, numpy, idna, charset-normalizer, certifi, scipy, requests, python-dateutil, simpful, pandas, miniful, fst-pso, pyfume, FuzzyTM, gensim
  Running setup.py install for miniful ... done
  Running setup.py install for fst-pso ... done
Successfully installed FuzzyTM-2.0.5 certifi-2022.12.7 charset-normalizer-2.1.1 fst-pso-1.8.1 gensim-4.3.0 idna-3.4 miniful-0.0.6 numpy-1.24.1 pandas-1.5.2 pyfume-0.2.25 python-dateutil-2.8.2 pytz-2022.7 requests-2.28.1 scipy-1.10.0 simpful-2.9.0 six-1.16.0 smart-open-6.3.0 urllib3-1.26.13
```

The size of the venv has grown from 249MB to 318MB, an increase of 69MB.

Here is what `pipdeptree` shows - FuzzyTM appears to be the main reason why so many libraries are pulled in:

```
gensim==4.3.0
  - FuzzyTM [required: >=0.4.0, installed: 2.0.5]
    - numpy [required: Any, installed: 1.24.1]
    - pandas [required: Any, installed: 1.5.2]
      - numpy [required: >=1.21.0, installed: 1.24.1]
      - python-dateutil [required: >=2.8.1, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - pytz [required: >=2020.1, installed: 2022.7]
    - pyfume [required: Any, installed: 0.2.25]
      - fst-pso [required: Any, installed: 1.8.1]
        - miniful [required: Any, installed: 0.0.6]
          - numpy [required: >=1.12.0, installed: 1.24.1]
          - scipy [required: >=1.0.0, installed: 1.10.0]
            - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
        - numpy [required: Any, installed: 1.24.1]
      - numpy [required: Any, installed: 1.24.1]
      - scipy [required: Any, installed: 1.10.0]
        - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
      - simpful [required: Any, installed: 2.9.0]
        - numpy [required: >=1.12.0, installed: 1.24.1]
        - requests [required: Any, installed: 2.28.1]
          - certifi [required: >=2017.4.17, installed: 2022.12.7]
          - charset-normalizer [required: >=2,<3, installed: 2.1.1]
          - idna [required: >=2.5,<4, installed: 3.4]
          - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.13]
        - scipy [required: >=1.0.0, installed: 1.10.0]
          - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
    - scipy [required: Any, installed: 1.10.0]
      - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
  - numpy [required: >=1.18.5, installed: 1.24.1]
  - scipy [required: >=1.7.0, installed: 1.10.0]
    - numpy [required: >=1.19.5,<1.27.0, installed: 1.24.1]
  - smart-open [required: >=1.8.1, installed: 6.3.0]
pip==22.0.2
pipdeptree==2.3.3
setuptools==59.6.0
```

It appears that the FuzzyTM dependency was added in PR #3398 (Flsamodel) by @ERijck . The first commits in this PR depended on the library, but a subsequent commit 9fec00b32d281e795f3b4701bf11fa1c97780227 reworked the code so it doesn't need to import FuzzyTM at all. But the dependency in setup.py wasn't actually removed, it's still there: https://github.com/RaRe-Technologies/gensim/blob/f35faae7a7b0c3c8586fb61208560522e37e0e7e/setup.py#L347

I think the FuzzyTM dependency could be safely dropped, as the library is not actually imported. It would reduce the number of libraries Gensim pulls in and thus reduce the size of installations, including Docker images where minimal size is often required.

#### Versions

I'm using Ubuntu Linux 22.04.

Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Bits 64
NumPy 1.24.1
SciPy 1.10.0
gensim 4.3.0
FAST_VERSION 0

### PR DESCRIPTION
**Pull request by ERijck**
Removed the FuzzyTM dependency from `setup.py`. Fixes #3423.

### CODE REVIEW

**Comment by piskvorky** [comment]
This PR seems huge – didn't we want to just remove one line from `setup.py`?

**Comment by ERijck** [comment]
Sorry, I thought that's what I did. I will aim to do it again today.

**Comment by osma** [comment]
@ERijck I think you are reusing an old branch `flsamodel` for this PR. It would be better to create a new branch instead, make the one-line commit there, and then open a PR.

**Comment by piskvorky** [comment]
That's weird. The previous commits should already be a part of `develop`, from the (already merged) #3398. Github shouldn't show them in the diff.

@mpenkov did we revert that PR or something? Where did commits like 6c7183e go.

**Comment by osma** [comment]
Looking at this from the outside: I think the PR got merged (into `develop`) and rebased/squashed/whatever at the same time. Thus the commit IDs are different on the original PR branch and the `develop` branch.

Normally you abandon (often delete entirely) the PR branch after merging it to `main`/`master`/`develop`/whatever. It's not good practice to keep adding commits to a PR branch after it's been merged.

Anyway the solution is to create a new branch with just a single one-line commit.

**Comment by piskvorky** [comment]
That would explain it. Squashing is against our policy, so that's an omission. A double whammy :)

Anyway yes, a solution is to branch off `develop` and do the necessary change. I'm thinking presenting a more user-friendly error when the `fuzzytm` import fails is also worthwhile (similar to how we handle other optional dependencies).

Let's see if any tests fail after changing the setup.py.

**Comment by osma** [comment]
> Squashing is against our policy, so that's another omission – a double whammy :)

It seems to me that all recent PR merges [on the `develop` branch](https://github.com/RaRe-Technologies/gensim/commits/develop) were done by squashing commits. Not just this one.

> I'm thinking presenting a more user-friendly error when the fuzzytm import fails is also worthwhile (similar to how we handle other optional dependencies).

There is no fuzzytm import in the current code base, so I don't see how it could fail...

**Comment by ERijck** [comment]
Sorry, I am relatively new to the git workflow and still learning. I have created a new branch and added, committed and pushed the new `setup.py` (without fuzzytm dependency) file. However, the new PR still shows previous commits. This must be the squashing you are referring to. Is it correct that I should remove previous commits from `develop` and then only add/commit the removal of fuzzytm dependency?

**Comment by osma** [comment]
@ERijck

Switch to your local `develop` branch:

    git checkout develop

Make sure your local `develop` branch is in sync with the origin `develop` branch (e.g. do a `git pull origin develop`).

Then create a new branch as a fork of the `develop` branch:

    git checkout -b remove-fuzzytm-dependency

Edit `setup.py`, commit, push.

Alternatively, you can do this directly from the GitHub UI. Navigate to `setup.py`, click the edit button (pencil icon), make the change, commit and save it as a new pull request.

**Comment by piskvorky** [comment]
> It seems to me that all recent PR merges [on the `develop` branch](https://github.com/RaRe-Technologies/gensim/commits/develop) were done by squashing commits. Not just this one.

@mpenkov did I miss something, are we squashing PRs now?

I'm personally not a fan of rewriting history (and not only for the reasons manifested in this ticket). I'd strongly prefer normal merges.

**Comment by ERijck** [comment]
I have precisely followed @osma's advised steps (as described below). For this, I have created a new pull request #3437. Still, all these previous commits are there. 

> @ERijck
> 
> Switch to your local `develop` branch:
> 
> ```
> git checkout develop
> ```
> 
> Make sure your local `develop` branch is in sync with the origin `develop` branch (e.g. do a `git pull origin develop`).
> 
> Then create a new branch as a fork of the `develop` branch:
> 
> ```
> git checkout -b remove-fuzzytm-dependency
> ```
> 
> Edit `setup.py`, commit, push.
> 
> Alternatively, you can do this directly from the GitHub UI. Navigate to `setup.py`, click the edit button (pencil icon), make the change, commit and save it as a new pull request.

**Comment by piskvorky** [comment]
Commits are also a measure of past effort (of the PR, of project), as well as authorship and author footprint & effort.

And then there's bisecting to locate errors; informative commit messages (hopefully) related to a concrete commit = set of changes etc.

Btw commits are never "a part of the history of the branch they are being merged into"… until they're merged :) Not sure what you meant.

In any case, the path here is clear:

1. Remove the overlooked dependency.
2. Check that all tests pass, and that any import errors we introduced are meaningful. For example, I see some `pyfume` import in `flsamodel.py` – what will happen to it when 
3. Release a bugfix.

@ERijck if you follow @osma's steps above, you should get a branch with a single extra commit in it. This PR has 7 commits in it, which doesn't sound right.

**Comment by osma** [comment]
@ERijck I suspect that your local `develop` branch may not be in sync with the origin `develop` branch. It may already have the commits from your older PR branch. Thus when you fork a new branch off of your local `develop` branch, it already comes with some "extra" commits.

There are many ways to fix this but perhaps the easiest (even if it's a bit drastic) is to delete your local `develop` branch and then pull it again from origin.

**Comment by ERijck** [comment]
Finally, it worked. I will add an `ImportError` and write documentation explicitly mentioning how to install `pyfume`. 

Thanks for the help and patience @piskvorky, @osma and @mpenkov!

**Pull request closed without merging**
