### PR TITLE
Dictionary Coloring

### PR DESCRIPTION
**Pull request by bhargavvader**
This is an update for the word-colouring notebook - I've had some requests about how to statically color a dictionary, and have demonstrated the same in the notebook.

### CODE REVIEW

**Comment by tmylk** [comment]
Could you please clarify  what is the reason for the incorrect coloring of 'mud'? Lack of context in `get_term_topics` or in the corpus?

**Comment by bhargavvader** [comment]
I reckon it's because of the small vocabulary the lda model isn't trained perfectly; will investigate and see the exact reason.

**Comment by tmylk** [comment]
could you please remove/correct the text about it? will merge after it's fixed

**Comment by bhargavvader** [comment]
Sorry, been busy last couple of days. Would you just like the text to be removed? I thought I could spend some time in fixing it by fine-tuning the model.

**Comment by tmylk** [comment]
Just need to be explicit in that the coloring is correct according to the model. But the model is wrong because of small corpus.

**Comment by bhargavvader** [comment]
Sorry about the delay - I've added a small explanation now.

**Comment by bhargavvader** [comment]
@tmylk unrelated tests failing.

**Comment by tmylk** [comment]
Travis tests re-ran after smart_open update

**Comment by tmylk** [comment]
Thx for the update!

**Pull request merged**
